#include "axllm/runtime/quickjs/quickjs_runtime.hpp"

#include <chrono>
#include <cstring>
#include <vector>

namespace axllm::runtime::quickjs {

static std::vector<std::pair<std::string, Value>> value_entries(Value value) {
  std::vector<std::pair<std::string, Value>> out;
  for (const auto& key_value : Core::iter(Core::map_keys(value))) {
    std::string key = display(key_value);
    out.push_back({key, Core::get(value, key)});
  }
  return out;
}

static bool contains_name(Value values, const std::string& name) {
  for (const auto& item : Core::iter(values)) {
    if (display(item) == name) return true;
  }
  return false;
}

static bool is_host_callable(Value value) {
  return value.is_object() && Core::truthy(Core::get(value, "__ax_host_callable", Value(false)));
}

static int int_option(Value options, const std::string& key, int fallback) {
  Value value = Core::get(options, key);
  if (value.is_null()) return fallback;
  try {
    int parsed = static_cast<int>(std::stod(display(value)));
    return parsed < 1 ? 1 : parsed;
  } catch (...) {
    return fallback;
  }
}

static Value default_runtime_policy(Value overrides = Value::object()) {
  Value policy = object({
      {"allowFilesystem", false},
      {"allowNetwork", false},
      {"allowProcess", false},
      {"allowNativeHostAccess", false},
      {"maxSnapshotBytes", 262144},
      {"memoryLimitBytes", 32 * 1024 * 1024},
      {"timeoutMs", 5000},
  });
  for (const auto& entry : value_entries(overrides)) {
    Core::set(policy, entry.first, entry.second);
  }
  return policy;
}

static Value merge_runtime_policy(Value base, Value options) {
  Value policy = default_runtime_policy(std::move(base));
  Value overrides = Core::get(options, "runtimePolicy", Value::object());
  for (const auto& entry : value_entries(overrides)) {
    Core::set(policy, entry.first, entry.second);
  }
  return policy;
}

static const char* bootstrap_source = R"JS(
var __ax_host_namespaces = Object.create(null);
function __ax_bind_host_namespaces() {
  const roots = [];
  for (const name of Object.getOwnPropertyNames(globalThis)) {
    if (name.indexOf('.') < 0) continue;
    const callable = Object.getOwnPropertyDescriptor(globalThis, name);
    if (!callable || typeof callable.value !== 'function') continue;
    const parts = name.split('.');
    if (parts.some(part => !part)) {
      throw new Error('Invalid host callable namespace: ' + name);
    }
    let target = globalThis;
    let path = '';
    for (let index = 0; index < parts.length - 1; index++) {
      const part = parts[index];
      path += (index ? '.' : '') + part;
      let entry = Object.getOwnPropertyDescriptor(target, part);
      if (!entry) {
        const value = Object.create(null);
        Object.defineProperty(target, part, {value, enumerable: true});
        __ax_host_namespaces[path] = value;
        entry = {value};
      }
      if (entry.value !== __ax_host_namespaces[path]) {
        throw new Error('Host callable namespace conflicts with a global: ' + path);
      }
      target = entry.value;
    }
    const leaf = parts[parts.length - 1];
    const existing = Object.getOwnPropertyDescriptor(target, leaf);
    if (existing && existing.value !== callable.value) {
      throw new Error('Host callable name conflicts with a namespace: ' + name);
    }
    if (!existing) Object.defineProperty(target, leaf, {value: callable.value, enumerable: true});
    if (roots.indexOf(parts[0]) < 0) roots.push(parts[0]);
  }
  if (Array.isArray(globalThis.__ax_session_reserved)) {
    for (const root of roots) {
      if (globalThis.__ax_session_reserved.indexOf(root) < 0) globalThis.__ax_session_reserved.push(root);
    }
  }
  return roots;
}

// Generated by scripts/axir-runtime-support.mjs from
// src/ax/util/jsAnalysis.ts, src/ax/agent/contextManager.ts and
// src/ax/funcs/worker.runtime.ts. Do not edit by hand.
(function () {
function isIdentifierChar(ch) {
  return !!ch && /[A-Za-z0-9_$]/.test(ch);
}
function isIdentifierStart(ch) {
  return !!ch && /[A-Za-z_$]/.test(ch);
}
function stripJsStringsAndComments(code) {
  var _a, _b;
  let out = "";
  let i = 0;
  let state = "normal";
  let escaped = false;
  while (i < code.length) {
    const ch = (_a = code[i]) != null ? _a : "";
    const next = (_b = code[i + 1]) != null ? _b : "";
    if (state === "lineComment") {
      if (ch === "\n") {
        out += "\n";
        state = "normal";
      } else {
        out += " ";
      }
      i++;
      continue;
    }
    if (state === "blockComment") {
      if (ch === "*" && next === "/") {
        out += "  ";
        i += 2;
        state = "normal";
      } else {
        out += ch === "\n" ? "\n" : " ";
        i++;
      }
      continue;
    }
    if (state === "single" || state === "double" || state === "template") {
      const quote = state === "single" ? "'" : state === "double" ? '"' : "`";
      if (escaped) {
        out += ch === "\n" ? "\n" : " ";
        escaped = false;
        i++;
        continue;
      }
      if (ch === "\\") {
        out += " ";
        escaped = true;
        i++;
        continue;
      }
      if (ch === quote) {
        out += " ";
        state = "normal";
        i++;
        continue;
      }
      out += ch === "\n" ? "\n" : " ";
      i++;
      continue;
    }
    if (ch === "/" && next === "/") {
      out += "  ";
      i += 2;
      state = "lineComment";
      continue;
    }
    if (ch === "/" && next === "*") {
      out += "  ";
      i += 2;
      state = "blockComment";
      continue;
    }
    if (ch === "'") {
      out += " ";
      i++;
      state = "single";
      continue;
    }
    if (ch === '"') {
      out += " ";
      i++;
      state = "double";
      continue;
    }
    if (ch === "`") {
      out += " ";
      i++;
      state = "template";
      continue;
    }
    out += ch;
    i++;
  }
  return out;
}
function extractTopLevelDeclaredNames(code) {
  const names = [];
  const len = code.length;
  let i = 0;
  let braceDepth = 0;
  let parenDepth = 0;
  const skipString = (quote) => {
    i++;
    if (quote === "`") {
      let templateDepth = 0;
      while (i < len) {
        const ch = code[i];
        if (ch === "\\") {
          i += 2;
          continue;
        }
        if (templateDepth > 0) {
          if (ch === "{") {
            templateDepth++;
          } else if (ch === "}") {
            templateDepth--;
          }
          i++;
          continue;
        }
        if (ch === "$" && i + 1 < len && code[i + 1] === "{") {
          templateDepth++;
          i += 2;
          continue;
        }
        if (ch === "`") {
          i++;
          return;
        }
        i++;
      }
      return;
    }
    while (i < len) {
      const ch = code[i];
      if (ch === "\\") {
        i += 2;
        continue;
      }
      if (ch === quote) {
        i++;
        return;
      }
      i++;
    }
  };
  const skipLineComment = () => {
    i += 2;
    while (i < len && code[i] !== "\n") {
      i++;
    }
  };
  const skipBlockComment = () => {
    i += 2;
    while (i < len) {
      if (code[i] === "*" && i + 1 < len && code[i + 1] === "/") {
        i += 2;
        return;
      }
      i++;
    }
  };
  const readWord = () => {
    const start = i;
    while (i < len && isIdentifierChar(code[i])) {
      i++;
    }
    return code.slice(start, i);
  };
  const skipWhitespace = () => {
    const start = i;
    while (i < len) {
      const ch = code[i];
      if (ch === " " || ch === "	" || ch === "\n" || ch === "\r") {
        i++;
        continue;
      }
      if (ch === "/" && i + 1 < len) {
        if (code[i + 1] === "/") {
          skipLineComment();
          continue;
        }
        if (code[i + 1] === "*") {
          skipBlockComment();
          continue;
        }
      }
      break;
    }
    return i > start;
  };
  const extractDestructuredNames = (close) => {
    let depth = 1;
    while (i < len && depth > 0) {
      skipWhitespace();
      if (i >= len) return;
      const ch = code[i];
      if (ch === close) {
        depth--;
        i++;
        continue;
      }
      if (ch === "{" || ch === "[") {
        const nestedClose = ch === "{" ? "}" : "]";
        i++;
        extractDestructuredNames(nestedClose);
        continue;
      }
      if (ch === "." && i + 2 < len && code[i + 1] === "." && code[i + 2] === ".") {
        i += 3;
        skipWhitespace();
        if (i < len && isIdentifierChar(code[i])) {
          const name = readWord();
          if (name) names.push(name);
        }
        continue;
      }
      if (ch === ",") {
        i++;
        continue;
      }
      if (ch === "=") {
        i++;
        let eqDepth = 0;
        while (i < len) {
          const current = code[i];
          if (current === "'" || current === '"' || current === "`") {
            skipString(current);
            continue;
          }
          if (current === "(" || current === "[" || current === "{") {
            eqDepth++;
            i++;
            continue;
          }
          if (current === ")" || current === "]" || current === "}") {
            if (eqDepth > 0) {
              eqDepth--;
              i++;
              continue;
            }
            break;
          }
          if (current === "," && eqDepth === 0) {
            break;
          }
          i++;
        }
        continue;
      }
      if (isIdentifierChar(ch)) {
        const word = readWord();
        skipWhitespace();
        if (i < len && code[i] === ":") {
          i++;
          skipWhitespace();
          if (i < len) {
            const current = code[i];
            if (current === "{" || current === "[") {
              const nestedClose = current === "{" ? "}" : "]";
              i++;
              extractDestructuredNames(nestedClose);
            } else if (isIdentifierChar(current)) {
              const renamed = readWord();
              if (renamed) names.push(renamed);
            }
          }
        } else if (word) {
          names.push(word);
        }
        continue;
      }
      i++;
    }
  };
  const skipToCommaOrEnd = () => {
    let depth = 0;
    while (i < len) {
      const ch = code[i];
      if (ch === "'" || ch === '"' || ch === "`") {
        skipString(ch);
        continue;
      }
      if (ch === "/" && i + 1 < len) {
        if (code[i + 1] === "/") {
          skipLineComment();
          continue;
        }
        if (code[i + 1] === "*") {
          skipBlockComment();
          continue;
        }
      }
      if (ch === "(" || ch === "[" || ch === "{") {
        depth++;
        i++;
        continue;
      }
      if (ch === ")" || ch === "]" || ch === "}") {
        if (depth > 0) {
          depth--;
          i++;
          continue;
        }
        return false;
      }
      if (ch === "," && depth === 0) {
        i++;
        return true;
      }
      if (ch === ";" && depth === 0) {
        i++;
        return false;
      }
      if (ch === "\n" && depth === 0) {
        const savedIndex = i;
        i++;
        skipWhitespace();
        if (i < len && code[i] === ",") {
          i++;
          return true;
        }
        i = savedIndex;
        return false;
      }
      i++;
    }
    return false;
  };
  const extractBindings = () => {
    while (i < len) {
      skipWhitespace();
      if (i >= len) return;
      const ch = code[i];
      if (ch === "{") {
        i++;
        extractDestructuredNames("}");
        if (!skipToCommaOrEnd()) return;
        continue;
      }
      if (ch === "[") {
        i++;
        extractDestructuredNames("]");
        if (!skipToCommaOrEnd()) return;
        continue;
      }
      if (isIdentifierChar(ch)) {
        const name = readWord();
        if (name) names.push(name);
        if (!skipToCommaOrEnd()) return;
        continue;
      }
      return;
    }
  };
  const isStatementBoundary = (pos) => {
    if (pos === 0) return true;
    let j = pos - 1;
    while (j >= 0) {
      const ch = code[j];
      if (ch === " " || ch === "	" || ch === "\r") {
        j--;
        continue;
      }
      return ch === "\n" || ch === ";" || ch === "{" || ch === "}";
    }
    return true;
  };
  while (i < len) {
    const ch = code[i];
    if (ch === "'" || ch === '"' || ch === "`") {
      skipString(ch);
      continue;
    }
    if (ch === "/" && i + 1 < len) {
      if (code[i + 1] === "/") {
        skipLineComment();
        continue;
      }
      if (code[i + 1] === "*") {
        skipBlockComment();
        continue;
      }
    }
    if (ch === "{") {
      braceDepth++;
      i++;
      continue;
    }
    if (ch === "}") {
      braceDepth--;
      i++;
      continue;
    }
    if (ch === "(") {
      parenDepth++;
      i++;
      continue;
    }
    if (ch === ")") {
      parenDepth--;
      i++;
      continue;
    }
    if (braceDepth === 0 && parenDepth === 0 && isIdentifierChar(ch)) {
      const wordStart = i;
      const word = readWord();
      if ((word === "var" || word === "let" || word === "const") && i < len && (code[i] === " " || code[i] === "	" || code[i] === "\n") && isStatementBoundary(wordStart)) {
        extractBindings();
      }
      continue;
    }
    i++;
  }
  const seen = /* @__PURE__ */ new Set();
  const unique = [];
  for (const name of names) {
    if (!seen.has(name)) {
      seen.add(name);
      unique.push(name);
    }
  }
  return unique;
}
function extractTopLevelDurableWriteTargets(code) {
  const names = new Set(extractTopLevelDeclaredNames(code));
  const sanitized = stripJsStringsAndComments(code);
  const len = sanitized.length;
  let i = 0;
  let braceDepth = 0;
  let parenDepth = 0;
  const skipWhitespace = (index) => {
    var _a;
    let current = index;
    while (current < len && /\s/.test((_a = sanitized[current]) != null ? _a : "")) {
      current++;
    }
    return current;
  };
  const previousNonWhitespaceIndex = (index) => {
    var _a;
    let current = index;
    while (current >= 0 && /\s/.test((_a = sanitized[current]) != null ? _a : "")) {
      current--;
    }
    return current;
  };
  const isAssignmentOperatorAt = (index) => {
    const threeChars = sanitized.slice(index, index + 3);
    const twoChars = sanitized.slice(index, index + 2);
    if (threeChars === "===" || twoChars === "==" || twoChars === "=>") {
      return false;
    }
    return sanitized[index] === "=" || [
      "+=",
      "-=",
      "*=",
      "/=",
      "%=",
      "&=",
      "|=",
      "^=",
      "&&=",
      "||=",
      "??=",
      "**=",
      "<<=",
      ">>=",
      ">>>="
    ].some((op) => sanitized.startsWith(op, index));
  };
  const readWord = (start) => {
    let nextIndex = start;
    while (nextIndex < len && isIdentifierChar(sanitized[nextIndex])) {
      nextIndex++;
    }
    return { word: sanitized.slice(start, nextIndex), nextIndex };
  };
  const addIfBareAssignment = (word, start, end) => {
    const prevIndex = previousNonWhitespaceIndex(start - 1);
    const prev = prevIndex >= 0 ? sanitized[prevIndex] : void 0;
    const nextIndex = skipWhitespace(end);
    const isMemberAccess = prev === "." || prev === "?";
    if (isMemberAccess) {
      return;
    }
    const hasPrefixUpdate = sanitized.slice(Math.max(0, start - 2), start) === "++" || sanitized.slice(Math.max(0, start - 2), start) === "--";
    const hasSuffixUpdate = sanitized.startsWith("++", nextIndex) || sanitized.startsWith("--", nextIndex);
    if (hasPrefixUpdate || hasSuffixUpdate || isAssignmentOperatorAt(nextIndex)) {
      names.add(word);
    }
  };
  const addIfGlobalAssignment = (start, end) => {
    const dotIndex = skipWhitespace(end);
    if (sanitized[dotIndex] !== ".") {
      return;
    }
    const nameStart = skipWhitespace(dotIndex + 1);
    if (!isIdentifierStart(sanitized[nameStart])) {
      return;
    }
    const { word: propertyName, nextIndex } = readWord(nameStart);
    const operatorIndex = skipWhitespace(nextIndex);
    const hasPrefixUpdate = sanitized.slice(Math.max(0, start - 2), start) === "++" || sanitized.slice(Math.max(0, start - 2), start) === "--";
    const hasSuffixUpdate = sanitized.startsWith("++", operatorIndex) || sanitized.startsWith("--", operatorIndex);
    if (propertyName && (hasPrefixUpdate || hasSuffixUpdate || isAssignmentOperatorAt(operatorIndex))) {
      names.add(propertyName);
    }
  };
  while (i < len) {
    const ch = sanitized[i];
    if (ch === "{") {
      braceDepth++;
      i++;
      continue;
    }
    if (ch === "}") {
      braceDepth--;
      i++;
      continue;
    }
    if (ch === "(") {
      parenDepth++;
      i++;
      continue;
    }
    if (ch === ")") {
      parenDepth--;
      i++;
      continue;
    }
    if (braceDepth === 0 && parenDepth === 0 && isIdentifierStart(ch)) {
      const start = i;
      const { word, nextIndex } = readWord(i);
      i = nextIndex;
      if (!word) {
        continue;
      }
      if (word === "globalThis") {
        addIfGlobalAssignment(start, nextIndex);
        continue;
      }
      addIfBareAssignment(word, start, nextIndex);
      continue;
    }
    i++;
  }
  return [...names];
}
const JS_KEYWORDS = new Set([
  'var', 'let', 'const', 'function', 'return', 'if', 'else', 'for', 'while',
  'do', 'switch', 'case', 'break', 'continue', 'try', 'catch', 'finally',
  'throw', 'new', 'delete', 'typeof', 'void', 'in', 'of', 'instanceof',
  'this', 'class', 'extends', 'super', 'import', 'export', 'default', 'from',
  'as', 'async', 'await', 'yield', 'true', 'false', 'null', 'undefined',
  'console', 'log'
]);
function extractReferencedIdentifiers(code) {
  const sanitized = stripJsStringsAndComments(code);
  const identRegex = /\b([a-zA-Z_$][a-zA-Z0-9_$]*)\b/g;
  const ids = new Set();
  let match = identRegex.exec(sanitized);
  while (match !== null) {
    if (match[1] && !JS_KEYWORDS.has(match[1])) {
      ids.add(match[1]);
    }
    match = identRegex.exec(sanitized);
  }
  return ids;
}
function extractReadIdentifiers(code) {
  const reads = extractReferencedIdentifiers(code);
  for (const declared of extractTopLevelDeclaredNames(code)) {
    reads.delete(declared);
  }
  return reads;
}
function extractDirectQualifiedCallableUsages(code) {
  const sanitized = stripJsStringsAndComments(code);
  const usages = new Set();
  const callPattern = /\b([a-zA-Z_$][a-zA-Z0-9_$]*)\.([a-zA-Z_$][a-zA-Z0-9_$]*)\s*\(/g;
  let match = callPattern.exec(sanitized);
  while (match) {
    const namespace = match[1];
    const name = match[2];
    if (namespace && name) {
      usages.add(namespace + '.' + name);
    }
    match = callPattern.exec(sanitized);
  }
  return [...usages];
}
const truncateInspectText = (text, maxChars) =>
  text.length <= maxChars ? text : text.slice(0, maxChars - 3) + '...';
const previewInspectAtom = (value) => {
  if (value === null) {
    return 'null';
  }
  if (value === undefined) {
    return 'undefined';
  }
  const valueType = typeof value;
  if (typeof value === 'string') {
    return JSON.stringify(truncateInspectText(value, 40));
  }
  if (valueType === 'number' || valueType === 'boolean' || valueType === 'bigint') {
    return String(value);
  }
  if (valueType === 'symbol') {
    return String(value);
  }
  if (valueType === 'function') {
    const fnName = value.name && typeof value.name === 'string' ? value.name : '';
    return '[function ' + (fnName || 'anonymous') + ']';
  }
  if (Array.isArray(value)) {
    return '[array(' + value.length + ')]';
  }
  if (value instanceof Date) {
    return Number.isFinite(value.getTime()) ? value.toISOString() : String(value);
  }
  if (value instanceof Error) {
    return (value.name || 'Error') + ': ' + (value.message || '');
  }
  if (typeof Map !== 'undefined' && value instanceof Map) {
    return '[map(' + value.size + ')]';
  }
  if (typeof Set !== 'undefined' && value instanceof Set) {
    return '[set(' + value.size + ')]';
  }
  const ctorName =
    value && typeof value === 'object' && 'constructor' in value && value.constructor &&
    typeof value.constructor.name === 'string'
      ? value.constructor.name
      : '';
  return ctorName && ctorName !== 'Object' ? '[' + ctorName + ']' : '[object]';
};
const describeInspectType = (value) => {
  if (value === null) {
    return { type: 'null' };
  }
  if (Array.isArray(value)) {
    return { type: 'array', ctor: 'Array' };
  }
  if (typeof Map !== 'undefined' && value instanceof Map) {
    return { type: 'map', ctor: 'Map' };
  }
  if (typeof Set !== 'undefined' && value instanceof Set) {
    return { type: 'set', ctor: 'Set' };
  }
  if (value instanceof Date) {
    return { type: 'date', ctor: 'Date' };
  }
  if (value instanceof Error) {
    return {
      type: 'error',
      ctor: typeof value.name === 'string' && value.name.trim() ? value.name : 'Error',
    };
  }
  const valueType = typeof value;
  if (valueType !== 'object') {
    return { type: valueType };
  }
  const ctor =
    value && typeof value === 'object' && 'constructor' in value && value.constructor &&
    typeof value.constructor.name === 'string'
      ? value.constructor.name
      : undefined;
  return { type: 'object', ctor };
};
const describeInspectSize = (value, type) => {
  if (type === 'string') {
    return value.length + ' chars';
  }
  if (type === 'array') {
    return value.length + ' items';
  }
  if (type === 'map' || type === 'set') {
    return value.size + ' items';
  }
  if (type === 'object' && value && typeof value === 'object') {
    return Object.keys(value).length + ' keys';
  }
  return undefined;
};
const previewInspectValue = (value, type, ctor) => {
  if (type === 'array') {
    const items = value.slice(0, 3).map((item) => previewInspectAtom(item));
    return '[' + items.join(', ') + (value.length > 3 ? ', ...' : '') + ']';
  }
  if (type === 'map') {
    const items = Array.from(value.entries())
      .slice(0, 3)
      .map((pair) => previewInspectAtom(pair[0]) + ' => ' + previewInspectAtom(pair[1]));
    return 'Map(' + value.size + ') {' + items.join(', ') + (value.size > 3 ? ', ...' : '') + '}';
  }
  if (type === 'set') {
    const items = Array.from(value.values())
      .slice(0, 5)
      .map((item) => previewInspectAtom(item));
    return 'Set(' + value.size + ') {' + items.join(', ') + (value.size > 5 ? ', ...' : '') + '}';
  }
  if (type === 'date' || type === 'error' || type === 'function') {
    return previewInspectAtom(value);
  }
  if (type === 'object' && value && typeof value === 'object') {
    const keys = Object.keys(value);
    const shown = keys.slice(0, 4);
    const prefix = ctor && ctor !== 'Object' ? ctor + ' ' : '';
    return prefix + '{' + shown.join(', ') + (keys.length > shown.length ? ', ...' : '') + '}';
  }
  return previewInspectAtom(value);
};
const canCloneValue = (value, seen) => {
  const valueType = typeof value;
  if (valueType === 'function' || valueType === 'symbol') {
    return false;
  }
  if (value === null || valueType !== 'object') {
    return true;
  }
  if (seen.indexOf(value) >= 0) {
    return true;
  }
  seen.push(value);
  if (value instanceof Date || value instanceof RegExp || value instanceof Error) {
    return true;
  }
  if (typeof Map !== 'undefined' && value instanceof Map) {
    for (const pair of value.entries()) {
      if (!canCloneValue(pair[0], seen) || !canCloneValue(pair[1], seen)) return false;
    }
    return true;
  }
  if (typeof Set !== 'undefined' && value instanceof Set) {
    for (const item of value.values()) {
      if (!canCloneValue(item, seen)) return false;
    }
    return true;
  }
  for (const key of Object.keys(value)) {
    if (!canCloneValue(value[key], seen)) return false;
  }
  return true;
};
globalThis.__ax_analyze_code = function (code) {
  const text = typeof code === 'string' ? code : '';
  return JSON.stringify({
    producedVars: extractTopLevelDurableWriteTargets(text),
    readVars: [...extractReadIdentifiers(text)],
    callables: extractDirectQualifiedCallableUsages(text),
  });
};
// src/ax/agent/agentInternal/sharedSession.ts buildDistillerFinalWrapperCode:
// in the distiller phase, final(task, evidence) with an evidence object
// keeps it as the distilledContext global, which the executor inherits with
// the session. The runtime calls this after installing its final primitive;
// a merge patch (the executor phase) sets __ax_phase to 'executor'.
globalThis.__ax_install_final_evidence = function () {
  const hostFinal = globalThis.final;
  if (typeof hostFinal !== 'function' || hostFinal.__ax_final_evidence === true) {
    return;
  }
  const wrapped = function () {
    const context = arguments[1];
    if (
      globalThis.__ax_phase !== 'executor' &&
      arguments.length === 2 &&
      context !== null &&
      typeof context === 'object' &&
      !Array.isArray(context)
    ) {
      globalThis.distilledContext = context;
    }
    return hostFinal.apply(this, arguments);
  };
  wrapped.__ax_final_evidence = true;
  const descriptor = Object.getOwnPropertyDescriptor(globalThis, 'final') || {};
  try {
    if (descriptor.configurable === false) {
      globalThis.final = wrapped;
    } else {
      Object.defineProperty(globalThis, 'final', {
        value: wrapped,
        writable: descriptor.writable !== false,
        enumerable: descriptor.enumerable === true,
        configurable: true,
      });
    }
  } catch (_error) {
    // A final the runtime cannot replace keeps its behavior.
  }
};
globalThis.__ax_inspect_entries = function (skipNames) {
  const skip = new Set(Array.isArray(skipNames) ? skipNames : []);
  const scope = globalThis;
  const entries = Object.getOwnPropertyNames(scope)
    .filter((name) => !skip.has(name) && !name.startsWith('_'))
    .sort()
    .map((name) => {
      try {
        const descriptor = Object.getOwnPropertyDescriptor(scope, name);
        if (!descriptor) {
          return undefined;
        }
        if ('get' in descriptor && typeof descriptor.get === 'function' && !('value' in descriptor)) {
          return { name, type: 'accessor', preview: '[getter omitted]', restorable: false };
        }
        const value = 'value' in descriptor ? descriptor.value : scope[name];
        const meta = describeInspectType(value);
        const size = describeInspectSize(value, meta.type);
        const preview = previewInspectValue(value, meta.type, meta.ctor);
        const entry = { name, type: meta.type };
        if (meta.ctor) entry.ctor = meta.ctor;
        if (size) entry.size = size;
        if (preview) entry.preview = truncateInspectText(preview, 96);
        entry.restorable = canCloneValue(value, []);
        return entry;
      } catch (_error) {
        return { name, type: 'unknown', preview: '[unavailable]', restorable: false };
      }
    })
    .filter((entry) => entry !== undefined);
  return JSON.stringify(entries);
};
})();

const __ax_builtin_reserved = [
  "Object", "Function", "Array", "Number", "parseFloat", "parseInt", "Infinity", "NaN",
  "undefined", "Boolean", "String", "Symbol", "Date", "Promise", "RegExp", "Error",
  "AggregateError", "EvalError", "RangeError", "ReferenceError", "SyntaxError", "TypeError",
  "URIError", "globalThis", "JSON", "Math", "Reflect", "Proxy", "eval", "isFinite",
  "isNaN", "decodeURI", "decodeURIComponent", "encodeURI", "encodeURIComponent",
  "console", "final", "respond", "askClarification", "discover", "recall", "used", "reportSuccess",
  "reportFailure", "guideAgent"
];
// Persistence: top-level const/let/var declared this turn are block-scoped to the async
// wrapper and would vanish next turn, but the RLM prompt promises a long-running REPL.
// Extract the declared names so they can be assigned onto globalThis (which persists),
// mirroring the TS runtime. Fail-open.
function axPersistSuffix(src){try{var n=[],s={},re=/(?:^|[\n;{}])\s*(?:export\s+)?(?:async\s+)?(?:function|class|const|let|var)\s+([A-Za-z_$][A-Za-z0-9_$]*)/g,m;while((m=re.exec(src))){if(!s[m[1]]){s[m[1]]=1;n.push(m[1]);}}return n.map(function(x){return 'try{globalThis['+JSON.stringify(x)+']='+x+';}catch(__e){}';}).join('');}catch(__e){return '';}}
function __ax_has_name(values, name) {
  if (!Array.isArray(values)) return false;
  for (let i = 0; i < values.length; i++) {
    if (values[i] === name) return true;
  }
  return false;
}
// Capture console output so the actor's debug logging surfaces as `logs` instead of
// throwing ReferenceError (which would waste an actor step). Mirrors the TS/Python runtimes.
globalThis.__ax_logs = [];
function __ax_log() {
  var parts = Array.prototype.slice.call(arguments).map(function (x) {
    if (typeof x === "string") return x;
    try { return JSON.stringify(x); } catch (e) { return String(x); }
  });
  globalThis.__ax_logs.push(parts.join(" "));
}
globalThis.console = { log: __ax_log, error: __ax_log, warn: __ax_log, info: __ax_log, debug: __ax_log };
function __ax_complete(value) { globalThis.__ax_completion = value; return value; }
function __ax_clone_json(value) {
  if (value === undefined) return null;
  return JSON.parse(JSON.stringify(value));
}
function __ax_host_callable_error(message, category) {
  const error = new Error(String(message || "host callable failed"));
  error.error_category = String(category || "runtime");
  return error;
}
function __ax_make_host_callable(name, spec) {
  return function(params) {
    if (spec && spec.native === true) {
      const response = JSON.parse(globalThis.__ax_host_call(name, JSON.stringify(params === undefined ? null : params)));
      if (response.ok) return response.result;
      throw __ax_host_callable_error(response.error || ("host callable failed: " + name), response.category);
    }
    if (spec && spec.error) {
      throw __ax_host_callable_error(spec.error.message || spec.error.error || ("host callable failed: " + name), spec.error.category);
    }
    if (spec && Object.prototype.hasOwnProperty.call(spec, "result")) return __ax_clone_json(spec.result);
    return { kind: "result", result: null };
  };
}
function __ax_install_host_callables() {
  for (const key of Object.getOwnPropertyNames(globalThis)) {
    if (key.startsWith("__ax_")) continue;
    const value = globalThis[key];
    if (value && typeof value === "object" && value.__ax_host_callable === true) {
      globalThis[key] = __ax_make_host_callable(key, value);
    }
  }
  __ax_bind_host_namespaces();
}
function final() { return __ax_complete({ type: "final", args: Array.from(arguments) }); }
function respond() { return __ax_complete({ type: "respond", args: Array.from(arguments) }); }
function askClarification() { return __ax_complete({ type: "askClarification", args: Array.from(arguments) }); }
function discover(request) { return __ax_complete({ kind: "discover", discover: request }); }
function recall(request) { return __ax_complete({ kind: "recall", recall: request }); }
function used(idOrRequest, reason) {
  const payload = (idOrRequest && typeof idOrRequest === "object") ? idOrRequest : { id: idOrRequest };
  if (reason !== undefined && reason !== null) payload.reason = String(reason);
  return __ax_complete({ kind: "used", used: payload });
}
function reportSuccess(message) { return __ax_complete({ kind: "status", status: { type: "success", message: String(message || "") } }); }
function reportFailure(message) { return __ax_complete({ kind: "status", status: { type: "failed", message: String(message || "") } }); }
function guideAgent(guidance) { return __ax_complete({ type: "guide_agent", guidance: String(guidance || "") }); }
function __ax_snapshot_json() {
  const out = {};
  const sessionReserved = Array.isArray(globalThis.__ax_session_reserved) ? globalThis.__ax_session_reserved : [];
  for (const key of Object.getOwnPropertyNames(globalThis)) {
    if (key.startsWith("__ax_")) continue;
    if (__ax_has_name(__ax_builtin_reserved, key) || __ax_has_name(sessionReserved, key)) continue;
    if (__ax_has_name(globalThis.__ax_engine_globals, key)) continue;
    const value = globalThis[key];
    if (typeof value === "function" || typeof value === "undefined") continue;
    try { JSON.stringify(value); out[key] = value; } catch (_) {}
  }
  return JSON.stringify(out);
}
function __ax_clear_user_globals() {
  const sessionReserved = Array.isArray(globalThis.__ax_session_reserved) ? globalThis.__ax_session_reserved : [];
  for (const key of Object.getOwnPropertyNames(globalThis)) {
    if (key.startsWith("__ax_")) continue;
    if (__ax_has_name(__ax_builtin_reserved, key) || __ax_has_name(sessionReserved, key)) continue;
    if (__ax_has_name(globalThis.__ax_engine_globals, key)) continue;
    try { delete globalThis[key]; } catch (_) {}
  }
}
// The engine's own globals (Atomics, Map, the bootstrap functions, ...) are
// not user bindings: the snapshot leaves them out, a replacing patch keeps
// them, and a restored snapshot cannot overwrite them.
globalThis.__ax_engine_globals = Object.getOwnPropertyNames(globalThis);
)JS";

static int quickjs_interrupt_handler(JSRuntime*, void* opaque) {
  auto* deadline = static_cast<std::chrono::steady_clock::time_point*>(opaque);
  if (deadline == nullptr) return 0;
  return std::chrono::steady_clock::now() > *deadline ? 1 : 0;
}

static JSValue quickjs_host_call(JSContext* context, JSValueConst, int argc, JSValueConst* argv) {
  auto* session = static_cast<QuickJsCodeSession*>(JS_GetContextOpaque(context));
  if (session == nullptr || argc < 2) return JS_NewString(context, "{\"ok\":false,\"category\":\"runtime\",\"error\":\"invalid QuickJS host call\"}");
  const char* raw_name = JS_ToCString(context, argv[0]);
  const char* raw_params = JS_ToCString(context, argv[1]);
  std::string name = raw_name ? raw_name : "";
  std::string params = raw_params ? raw_params : "null";
  JS_FreeCString(context, raw_name);
  JS_FreeCString(context, raw_params);
  std::string out = session->call_host_json(name, params);
  return JS_NewString(context, out.c_str());
}

QuickJsCodeSession::QuickJsCodeSession(Value globals, Value options, Value runtime_policy, std::map<std::string, HostCallable> host_callables)
    : runtime_(JS_NewRuntime()), context_(nullptr), reserved_(Core::get(options, "reservedNames", Value::array())), runtime_policy_(merge_runtime_policy(std::move(runtime_policy), options)), host_callables_(std::move(host_callables)) {
  if (!runtime_) throw AxError("runtime", "failed to create QuickJS runtime");
  JS_SetMemoryLimit(runtime_, static_cast<size_t>(int_option(runtime_policy_, "memoryLimitBytes", 32 * 1024 * 1024)));
  context_ = JS_NewContext(runtime_);
  if (!context_) throw AxError("runtime", "failed to create QuickJS context");
  JS_SetContextOpaque(context_, this);
  JSValue global = JS_GetGlobalObject(context_);
  JS_SetPropertyStr(context_, global, "__ax_host_call", JS_NewCFunction(context_, quickjs_host_call, "__ax_host_call", 2));
  JS_FreeValue(context_, global);
  JS_FreeValue(context_, JS_Eval(context_, bootstrap_source, std::strlen(bootstrap_source), "<ax-bootstrap>", JS_EVAL_TYPE_GLOBAL));
  engine_globals_ = eval_json("JSON.stringify(globalThis.__ax_engine_globals)");
  set_global("__ax_session_reserved", reserved_);
  for (const auto& entry : value_entries(globals)) {
    if (is_host_callable(entry.second) && !contains_name(reserved_, entry.first)) Core::append(reserved_, entry.first);
    set_global(entry.first, entry.second);
  }
  for (const auto& entry : host_callables_) {
    if (!contains_name(reserved_, entry.first)) Core::append(reserved_, entry.first);
    set_global(entry.first, object({{"__ax_host_callable", true}, {"native", true}}));
  }
  set_global("__ax_session_reserved", reserved_);
  JS_FreeValue(context_, JS_Eval(context_, "__ax_install_host_callables()", std::strlen("__ax_install_host_callables()"), "<ax-host-callables>", JS_EVAL_TYPE_GLOBAL));
  baseline_ = eval_json("JSON.stringify(Object.getOwnPropertyNames(globalThis))");
}

QuickJsCodeSession::~QuickJsCodeSession() {
  if (context_) JS_FreeContext(context_);
  if (runtime_) JS_FreeRuntime(runtime_);
}

Value QuickJsCodeSession::execute(Value code, Value options) {
  if (closed_) return RuntimeEnvelope::session_closed("session closed");
  std::string source = display(code);
  // TS's analysis of the turn's code: the top-level variables it writes and
  // reads, and its qualified calls.
  Value analysis;
  {
    JSValue global = JS_GetGlobalObject(context_);
    JS_SetPropertyStr(context_, global, "__ax_code", JS_NewStringLen(context_, source.c_str(), source.size()));
    JS_FreeValue(context_, global);
    try {
      analysis = eval_json("__ax_analyze_code(globalThis.__ax_code || '')");
    } catch (...) {
      analysis = Value();
    }
  }
  Value out = execute_turn(source, options);
  if (out.is_object() && analysis.is_object()) Core::set(out, "analysis", analysis);
  return out;
}

Value QuickJsCodeSession::execute_turn(const std::string& source, Value options) {
  int timeout_ms = int_option(options, "timeoutMs", int_option(runtime_policy_, "timeoutMs", 5000));
  auto deadline = std::chrono::steady_clock::now() + std::chrono::milliseconds(timeout_ms);
  JS_SetInterruptHandler(runtime_, quickjs_interrupt_handler, &deadline);
  static const char kBeforeExecute[] =
      "globalThis.__ax_completion = undefined; globalThis.__ax_error = undefined; globalThis.__ax_error_category = undefined; globalThis.__ax_logs = []; __ax_install_host_callables(); __ax_install_final_evidence();";
  JS_FreeValue(context_, JS_Eval(context_, kBeforeExecute, std::strlen(kBeforeExecute), "<ax-before-execute>", JS_EVAL_TYPE_GLOBAL));
  // RLM actor code uses top-level await (`await final(...)`), illegal in a plain script eval.
  // Pass the code in via a global string (avoids host-side JS escaping) and run it through the
  // AsyncFunction constructor so await is legal; then drain the job queue so awaited
  // continuations and the synchronous host primitives that set __ax_completion run.
  {
    JSValue global = JS_GetGlobalObject(context_);
    JS_SetPropertyStr(context_, global, "__ax_code", JS_NewStringLen(context_, source.c_str(), source.size()));
    JS_FreeValue(context_, global);
  }
  static const char kRunActor[] =
      "(async function(){}).constructor('with (globalThis) {\\n' + (globalThis.__ax_code || '') + '\\n' + axPersistSuffix(globalThis.__ax_code || '') + '\\n}')()"
      ".then(function(){}, function(e){ globalThis.__ax_error_category = String((e && (e.error_category || e.category)) || 'runtime'); globalThis.__ax_error = String((e && e.message) ? ((e.name ? e.name + ': ' : '') + e.message + (e.stack ? (' ' + e.stack) : '')) : ((e && e.stack) ? e.stack : e)); });";
  JSValue result = JS_Eval(context_, kRunActor, std::strlen(kRunActor), "<actor>", JS_EVAL_TYPE_GLOBAL);
  if (JS_IsException(result)) {
    JSValue exception = JS_GetException(context_);
    const char* text = JS_ToCString(context_, exception);
    std::string message = text ? text : "QuickJS exception";
    JS_FreeCString(context_, text);
    JS_FreeValue(context_, exception);
    JS_SetInterruptHandler(runtime_, nullptr, nullptr);
    if (std::chrono::steady_clock::now() > deadline || message.find("interrupted") != std::string::npos) {
      return RuntimeEnvelope::timeout("QuickJS execution timed out");
    }
    return RuntimeEnvelope::error(message, "runtime");
  }
  JS_FreeValue(context_, result);
  {
    JSContext* pending_ctx = nullptr;
    while (JS_ExecutePendingJob(runtime_, &pending_ctx) > 0) {
    }
  }
  JSValue actor_error = JS_Eval(context_, "globalThis.__ax_error === undefined ? null : globalThis.__ax_error", std::strlen("globalThis.__ax_error === undefined ? null : globalThis.__ax_error"), "<ax-error>", JS_EVAL_TYPE_GLOBAL);
  if (!JS_IsNull(actor_error) && !JS_IsUndefined(actor_error)) {
    const char* etext = JS_ToCString(context_, actor_error);
    std::string emsg = etext ? etext : "QuickJS actor error";
    JSValue actor_category = JS_Eval(context_, "globalThis.__ax_error_category === undefined ? 'runtime' : globalThis.__ax_error_category", std::strlen("globalThis.__ax_error_category === undefined ? 'runtime' : globalThis.__ax_error_category"), "<ax-error-category>", JS_EVAL_TYPE_GLOBAL);
    const char* ctext = JS_ToCString(context_, actor_category);
    std::string category = ctext ? ctext : "runtime";
    JS_FreeCString(context_, etext);
    JS_FreeCString(context_, ctext);
    JS_FreeValue(context_, actor_category);
    JS_FreeValue(context_, actor_error);
    JS_SetInterruptHandler(runtime_, nullptr, nullptr);
    if (std::chrono::steady_clock::now() > deadline || emsg.find("interrupted") != std::string::npos) {
      return RuntimeEnvelope::timeout("QuickJS execution timed out");
    }
    return RuntimeEnvelope::error(emsg, category.empty() ? "runtime" : category);
  }
  JS_FreeValue(context_, actor_error);
  result = JS_Eval(context_, "globalThis.__ax_completion === undefined ? {kind:'result', result:null} : globalThis.__ax_completion", std::strlen("globalThis.__ax_completion === undefined ? {kind:'result', result:null} : globalThis.__ax_completion"), "<ax-completion>", JS_EVAL_TYPE_GLOBAL);
  JSValue json = JS_JSONStringify(context_, result, JS_UNDEFINED, JS_UNDEFINED);
  const char* text = JS_ToCString(context_, json);
  std::string json_text = text ? text : "";
  JS_FreeCString(context_, text);
  JS_FreeValue(context_, json);
  JS_FreeValue(context_, result);
  JS_SetInterruptHandler(runtime_, nullptr, nullptr);
  if (json_text.empty() || json_text == "undefined") {
    return RuntimeEnvelope::error("QuickJS actor code did not return a JSON-compatible value", "runtime");
  }
  Value payload;
  try {
    payload = parse_json(json_text);
  } catch (const std::exception& error) {
    return RuntimeEnvelope::error(std::string("malformed QuickJS actor output: ") + error.what(), "runtime");
  }
  // Surface console output (captured into __ax_logs) as `logs`, mirroring the TS/Python runtimes.
  if (payload.is_object()) {
    Value logs = eval_json("JSON.stringify(globalThis.__ax_logs || [])");
    if (logs.is_array() && Core::truthy(Core::len(logs))) Core::set(payload, "logs", logs);
  }
  return payload;
}

Value QuickJsCodeSession::inspect(Value) { return eval_json("__ax_snapshot_json()"); }

Value QuickJsCodeSession::snapshot_globals(Value) {
  Value bindings = inspect(Value::object());
  int max_bytes = int_option(runtime_policy_, "maxSnapshotBytes", 262144);
  if (static_cast<int>(stringify(bindings).size()) > max_bytes) {
    Value trimmed = Value::object();
    for (const auto& entry : value_entries(bindings)) {
      Core::set(trimmed, entry.first, entry.second);
      if (static_cast<int>(stringify(trimmed).size()) > max_bytes) {
        Core::set(trimmed, entry.first, Value());
        Core::set(trimmed, "__ax_snapshot_truncated", true);
        bindings = trimmed;
        break;
      }
    }
  }
  return object({{"version", 1}, {"entries", inspect_entries()}, {"bindings", bindings}, {"globals", bindings}});
}

// TS's AxJSRuntime snapshot entries of the user globals.
Value QuickJsCodeSession::inspect_entries() {
  Value skip = Value::array();
  for (const auto& name : Core::iter(baseline_)) Core::append(skip, name);
  for (const auto& name : Core::iter(reserved_)) Core::append(skip, name);
  try {
    Value entries = eval_json("__ax_inspect_entries(" + stringify(skip) + ")");
    return entries.is_array() ? entries : Value::array();
  } catch (...) {
    return Value::array();
  }
}

Value QuickJsCodeSession::patch_globals(Value snapshot, Value) {
  // A merge patch (the agent's own globals for the executor, as TS's
  // patchGlobals) keeps the session's variables and updates its reserved
  // values; any other patch replaces the user globals.
  bool merge = Core::truthy(Core::get(snapshot, "merge", Value(false)));
  Value bindings = Core::get(snapshot, "bindings", snapshot);
  if (merge) {
    // The executor phase: the distiller's final no longer keeps evidence.
    static const char kExecutorPhase[] = "globalThis.__ax_phase = 'executor';";
    JS_FreeValue(context_, JS_Eval(context_, kExecutorPhase, std::strlen(kExecutorPhase), "<ax-phase>", JS_EVAL_TYPE_GLOBAL));
  } else {
    JS_FreeValue(context_, JS_Eval(context_, "__ax_clear_user_globals()", std::strlen("__ax_clear_user_globals()"), "<ax-clear>", JS_EVAL_TYPE_GLOBAL));
  }
  for (const auto& entry : value_entries(bindings)) {
    if (entry.first.rfind("__ax_", 0) == 0 || is_host_callable(entry.second)) continue;
    if (contains_name(reserved_, entry.first) && !merge) continue;
    // A snapshot saved before the engine's globals were left out (24.x
    // listed Atomics as a binding) must not overwrite them.
    if (contains_name(engine_globals_, entry.first)) continue;
    set_global(entry.first, entry.second);
  }
  return snapshot_globals(Value::object());
}

Value QuickJsCodeSession::close() {
  closed_ = true;
  return object({{"closed", true}});
}

std::string QuickJsCodeSession::call_host_json(const std::string& name, const std::string& params_json) {
  auto it = host_callables_.find(name);
  if (it == host_callables_.end()) {
    return stringify(object({{"ok", false}, {"category", "runtime"}, {"error", "unknown QuickJS host callable: " + name}}));
  }
  try {
    Value params = params_json.empty() ? Value() : parse_json(params_json);
    return stringify(object({{"ok", true}, {"result", it->second(params)}}));
  } catch (const AxError& error) {
    return stringify(object({{"ok", false}, {"category", error.category.empty() ? "runtime" : error.category}, {"error", std::string(error.what())}}));
  } catch (const std::exception& error) {
    return stringify(object({{"ok", false}, {"category", "runtime"}, {"error", std::string(error.what())}}));
  }
}

Value QuickJsCodeSession::eval_json(const std::string& source) {
  JSValue result = JS_Eval(context_, source.c_str(), source.size(), "<ax-inspect>", JS_EVAL_TYPE_GLOBAL);
  const char* text = JS_ToCString(context_, result);
  Value out = text ? parse_json(text) : Value::object();
  JS_FreeCString(context_, text);
  JS_FreeValue(context_, result);
  return out;
}

void QuickJsCodeSession::set_global(const std::string& name, const Value& value) {
  std::string source = "globalThis[" + stringify(Value(name)) + "] = JSON.parse(" + stringify(stringify(value)) + ");";
  JS_FreeValue(context_, JS_Eval(context_, source.c_str(), source.size(), "<ax-set-global>", JS_EVAL_TYPE_GLOBAL));
}

// TypeScript's AxJSRuntime.getUsageInstructions() in its default stdout mode.
std::string QuickJsCodeRuntime::usage_instructions() const {
  return "- Don't wrap async code in (async()=>{ ... })() \xe2\x80\x94 the runtime automatically handles async execution.\n"
         "- State is session-scoped: all top-level declarations (`var`, `let`, `const`) persist across calls.\n"
         "- Bare assignment (e.g. `x = 1`) also persists via `globalThis`.\n"
         "- Use `console.log(...)` output is captured as the execution result so use it to inspect intermediate values between steps instead of `return`.";
}

QuickJsCodeRuntime::QuickJsCodeRuntime(Value runtime_policy) : runtime_policy_(default_runtime_policy(std::move(runtime_policy))) {}

QuickJsCodeRuntime& QuickJsCodeRuntime::register_callable(std::string name, HostCallable handler) {
  if (name.empty()) throw AxError("runtime", "QuickJS host callable name is required");
  if (!handler) throw AxError("runtime", "QuickJS host callable handler is required");
  host_callables_[std::move(name)] = std::move(handler);
  return *this;
}

// Implements the package-neutral AxCodeRuntime seam (used by the agent wrapper
// to wire llmQuery); HostCallable is the same std::function<Value(Value)> type.
void QuickJsCodeRuntime::register_host_callable(std::string name, std::function<Value(Value)> callable) {
  if (!callable) return;
  register_callable(std::move(name), std::move(callable));
}

AxCodeSession* QuickJsCodeRuntime::create_session(Value globals, Value options) {
  return new QuickJsCodeSession(globals, options, runtime_policy_, host_callables_);
}

Value QuickJsCodeRuntime::runtime_policy() const { return runtime_policy_; }

}  // namespace axllm::runtime::quickjs
