package dev.axllm.ax;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.nio.charset.StandardCharsets;

/** Deterministic inline single-worker runtime. It owns no hidden worker thread. */
public final class AxEventRuntime {
  @FunctionalInterface public interface TargetInvoker { Object invoke(Object input, Map<String,Object> context) throws Exception; }
  @FunctionalInterface public interface InputMapper { Object map(AxEventEnvelope event, Continuation continuation) throws Exception; }
  public record Path(String root,List<Object> segments,String correlationKind,Object value) {
    public Path { for(Object segment:segments)if((segment instanceof String text&&(text.isEmpty()||text.equals("__proto__")||text.equals("constructor")||text.equals("prototype")))||(segment instanceof Number number&&number.longValue()<0))throw new IllegalArgumentException("Unsafe event path segment: "+segment); }
    public Map<String,Object> toMap(){Map<String,Object> out=new LinkedHashMap<>();out.put("root",root);out.put("segments",segments);if(correlationKind!=null)out.put("correlationKind",correlationKind);if(root.equals("constant"))out.put("value",value);return out;}
    public static Path data(Object...segments){return new Path("data",List.of(segments),null,null);}public static Path envelope(Object...segments){return new Path("envelope",List.of(segments),null,null);}public static Path subject(){return envelope("subject");}public static Path extension(String name){return new Path("extensions",List.of(name),null,null);}public static Path identity(Object...segments){return new Path("identity",List.of(segments),null,null);}public static Path trust(){return new Path("trust",List.of(),null,null);}public static Path correlation(String kind){return new Path("correlation",List.of(),kind,null);}public static Path continuation(Object...segments){return new Path("continuation",List.of(segments),null,null);}public static Path constant(Object value){return new Path("constant",List.of(),null,value);}
  }
  public record InputPlan(Path project,List<Map.Entry<String,Path>> fields){public Map<String,Object> toMap(){List<Map<String,Object>> mappings=new ArrayList<>();for(Map.Entry<String,Path> field:fields)mappings.add(Map.of("field",field.getKey(),"path",field.getValue().toMap()));Map<String,Object> out=new LinkedHashMap<>();if(project!=null)out.put("project",project.toMap());out.put("fields",mappings);return out;}}
  public static final class InputBuilder {private Path project;private final Map<String,Path> fields=new LinkedHashMap<>();public InputBuilder project(Path value){if(project!=null)throw new IllegalArgumentException("An event input plan may project only one path");project=value;return this;}public InputBuilder field(String name,Path value){if(fields.putIfAbsent(name,value)!=null)throw new IllegalArgumentException("Event input field "+name+" is mapped more than once");return this;}public InputPlan build(){return new InputPlan(project,List.copyOf(fields.entrySet()));}}
  public record PublishReceipt(String eventId,boolean accepted,boolean duplicate,String durability,List<String> deliveryIds) {}
  public static final class Run {
    public final String id,deliveryId,routeId,targetId,instanceKey;
    public String status="queued",error; public int attempt; public Object output; public final List<String> continuationIds=new ArrayList<>();
    Run(String id,String deliveryId,String routeId,String targetId,String instanceKey){this.id=id;this.deliveryId=deliveryId;this.routeId=routeId;this.targetId=targetId;this.instanceKey=instanceKey;}
  }
  public record DeadLetter(String id,String deliveryId,String runId,String sinkId,String reason) {}
  public static final class Continuation {
    public final String id,targetId,instanceKey,identityScope; public final List<Map<String,String>> correlation; public final Map<String,Object> metadata; public boolean completed;public final Long expiresAt;
    Continuation(String id,String targetId,String instanceKey,String identityScope,List<Map<String,String>> correlation,Map<String,Object> metadata,Long expiresAt){this.id=id;this.targetId=targetId;this.instanceKey=instanceKey;this.identityScope=identityScope;this.correlation=List.copyOf(correlation);this.metadata=Map.copyOf(metadata);this.expiresAt=expiresAt;}
  }
  public static final class CancellationToken { private volatile boolean cancelled;private volatile String reason;public void cancel(String reason){this.cancelled=true;this.reason=reason;}public boolean cancelled(){return cancelled;}public String reason(){return reason;} }
  public static final class Target {
    public final String id;final TargetInvoker invoke;InputMapper mapInput;final Map<String,AxEventSink> sinks=new LinkedHashMap<>();String retrySafety="unknown";final List<Map<String,Object>> waitFor=new ArrayList<>();java.util.function.Supplier<Object> captureState;java.util.function.Consumer<Object> restoreState;AxSignature signature;InputPlan input,wakeInput,resumeInput;
    public Target(String id,TargetInvoker invoke){this.id=id;this.invoke=invoke;}
    public Target mapInput(InputMapper value){mapInput=value;return this;}
    public Target signature(AxSignature value){signature=value;return this;}
    public Target input(java.util.function.Consumer<InputBuilder> mapping){InputBuilder value=new InputBuilder();mapping.accept(value);input=value.build();return this;}
    public Target wakeInput(java.util.function.Consumer<InputBuilder> mapping){InputBuilder value=new InputBuilder();mapping.accept(value);wakeInput=value.build();return this;}
    public Target resumeInput(java.util.function.Consumer<InputBuilder> mapping){InputBuilder value=new InputBuilder();mapping.accept(value);resumeInput=value.build();return this;}
    public Target sink(String id,AxEventSink value){sinks.put(id,value);return this;}
    public Target retrySafety(String value){retrySafety=value;return this;}
    public Target waitFor(String kind,String dataField,Map<String,Object> metadata){waitFor.add(Map.of("kind",kind,"value",dataField,"metadata",metadata));return this;}
    public Target waitFor(String kind,Path path,Map<String,Object> metadata){waitFor.add(Map.of("kind",kind,"value",path.toMap(),"metadata",metadata));return this;}
    public Target state(java.util.function.Supplier<Object> capture,java.util.function.Consumer<Object> restore){captureState=capture;restoreState=restore;return this;}
  }
  public static final class TargetBuilder {private final String id;private TargetInvoker invoker;private AxSignature signature;private InputMapper mapper;private java.util.function.Consumer<InputBuilder> input,wakeInput,resumeInput;private final List<Map.Entry<String,AxEventSink>> sinks=new ArrayList<>();private String retrySafety="unknown";private final List<Map<String,Object>> waits=new ArrayList<>();TargetBuilder(String id){this.id=id;}public TargetBuilder invoke(TargetInvoker value){invoker=value;return this;}public TargetBuilder signature(AxSignature value){signature=value;return this;}public TargetBuilder program(AxGen program,AiClient client){signature=program.signature;invoker=(value,context)->program.forward(client,Core.asMap(value));return this;}public TargetBuilder program(AxAgent program,AiClient client,AxSignature value){signature=value;invoker=(input,context)->program.forward(client,Core.asMap(input));return this;}public TargetBuilder program(AxFlow program,AiClient client,AxSignature value){signature=value;invoker=(input,context)->program.forward(client,Core.asMap(input));return this;}public TargetBuilder mapInput(InputMapper value){mapper=value;return this;}public TargetBuilder input(java.util.function.Consumer<InputBuilder> value){input=value;return this;}public TargetBuilder wakeInput(java.util.function.Consumer<InputBuilder> value){wakeInput=value;return this;}public TargetBuilder resumeInput(java.util.function.Consumer<InputBuilder> value){resumeInput=value;return this;}public TargetBuilder sink(String id,AxEventSink value){sinks.add(Map.entry(id,value));return this;}public TargetBuilder retrySafety(String value){retrySafety=value;return this;}public TargetBuilder waitFor(String kind,Path path,Map<String,Object> metadata){waits.add(Map.of("kind",kind,"value",path.toMap(),"metadata",metadata));return this;}public Target build(){if(invoker==null)throw new IllegalStateException("Event target requires an invoker or program");if(mapper!=null&&(input!=null||wakeInput!=null||resumeInput!=null))throw new IllegalStateException("Declarative mappings and mapInput are mutually exclusive");Target out=new Target(id,invoker).signature(signature).mapInput(mapper).retrySafety(retrySafety);if(input!=null)out.input(input);if(wakeInput!=null)out.wakeInput(wakeInput);if(resumeInput!=null)out.resumeInput(resumeInput);for(Map.Entry<String,AxEventSink> sink:sinks)out.sink(sink.getKey(),sink.getValue());out.waitFor.addAll(waits);return out;}}
  public static TargetBuilder eventTarget(String id){return new TargetBuilder(id);}
  public static final class RouteBuilder {private final String id;private final Map<String,Object> match=new LinkedHashMap<>();private boolean authenticated;private Path instanceKey;private String action,targetId;RouteBuilder(String id){this.id=id;}public RouteBuilder types(String...values){match.put("types",List.of(values));return this;}public RouteBuilder sources(String...values){match.put("sources",List.of(values));return this;}public RouteBuilder authenticated(){authenticated=true;return this;}public RouteBuilder instanceKey(Path value){instanceKey=value;return this;}public RouteBuilder wake(Target target){action="wake";targetId=target.id;return this;}public RouteBuilder resume(){action="resume";return this;}public RouteBuilder observe(){action="observe";return this;}public RouteBuilder invalidate(){action="invalidate";return this;}public AxEventRoute build(){if(action==null)throw new IllegalStateException("Event route requires one action");return new AxEventRoute(id,action,match,targetId,authenticated,"strict",0,instanceKey==null?null:instanceKey.toMap());}}
  public static RouteBuilder eventRoute(String id){return new RouteBuilder(id);}
  private static final class Delivery {final AxEventEnvelope event;final AxEventCommand command;String identityScope="anonymous",trust="untrusted",status="queued",runId;long availableAt,sequence,size;int attempt;Delivery(AxEventEnvelope event,AxEventCommand command,long availableAt,long sequence,long size){this.event=event;this.command=command;this.availableAt=availableAt;this.sequence=sequence;this.size=size;}}
  public static final class InMemoryStore implements AxEventStore {
    final Map<String,Delivery> deliveries=new LinkedHashMap<>();final Map<String,Run> runs=new LinkedHashMap<>();final Map<String,DeadLetter> deadLetters=new LinkedHashMap<>();final Map<String,Continuation> continuations=new LinkedHashMap<>();final Map<String,Object> programState=new LinkedHashMap<>();
    long queuedBytes,sequence;int maxPending=10_000;long maxQueuedBytes=64L*1024*1024,maxEnvelopeBytes=1024L*1024,publishTimeoutMs=5_000;AxEventClock clock;
    InMemoryStore(AxEventClock clock,Map<String,Object> options){this.clock=clock;maxPending=((Number)options.getOrDefault("maxPending",maxPending)).intValue();maxQueuedBytes=((Number)options.getOrDefault("maxQueuedBytes",maxQueuedBytes)).longValue();maxEnvelopeBytes=((Number)options.getOrDefault("maxEnvelopeBytes",maxEnvelopeBytes)).longValue();publishTimeoutMs=((Number)options.getOrDefault("publishTimeoutMs",publishTimeoutMs)).longValue();}
    synchronized void enqueue(AxEventEnvelope event,List<AxEventCommand> commands,long availableAt){long size=String.valueOf(event.toMap()).getBytes(StandardCharsets.UTF_8).length;if(size>maxEnvelopeBytes)throw new IllegalArgumentException("event envelope exceeds "+maxEnvelopeBytes+" bytes");List<AxEventCommand> fresh=new ArrayList<>();for(AxEventCommand command:commands)if(!deliveries.containsKey(command.routeId()+":"+event.id()))fresh.add(command);long deadline=clock.now()+publishTimeoutMs;while(!fresh.isEmpty()&&(pending()+fresh.size()>maxPending||queuedBytes+size*fresh.size()>maxQueuedBytes)){long remaining=deadline-clock.now();if(remaining<=0)throw new IllegalStateException("AxEventBackpressureError: event inbox capacity timed out");try{clock.sleep(Math.min(remaining,50));}catch(InterruptedException error){Thread.currentThread().interrupt();throw new IllegalStateException("event publication interrupted",error);}}for(AxEventCommand command:fresh){deliveries.put(command.routeId()+":"+event.id(),new Delivery(event,command,availableAt,++sequence,size));queuedBytes+=size;}}
    private int pending(){int count=0;for(Delivery value:deliveries.values())if(value.status.equals("queued"))count++;return count;}
    synchronized void release(Delivery delivery){queuedBytes=Math.max(0,queuedBytes-delivery.size);delivery.size=0;notifyAll();}
    synchronized void requeue(Delivery delivery,long availableAt){delivery.status="queued";delivery.availableAt=availableAt;delivery.size=String.valueOf(delivery.event.toMap()).getBytes(StandardCharsets.UTF_8).length;queuedBytes+=delivery.size;notifyAll();}
    public void enqueue(AxEventEnvelope event,List<AxEventCommand> commands){enqueue(event,commands,clock.now());}
  }
  public static final class PushSource implements AxEventSource {private java.util.function.Consumer<AxEventEnvelope> publish;private final String identityScope,trust;public PushSource(){this("anonymous","untrusted");}public PushSource(String identityScope,String trust){this.identityScope=identityScope;this.trust=trust;}public String identityScope(){return identityScope;}public String trust(){return trust;}public void start(java.util.function.Consumer<AxEventEnvelope> publish){this.publish=publish;}public void publish(AxEventEnvelope event){if(publish==null)throw new IllegalStateException("PushSource is not started");publish.accept(event);}public void close(){publish=null;}}

  private final List<AxEventRoute> routes;
  private final Map<String,Object> options;
  private final Map<String,Object> descriptor;
  private final InMemoryStore store;
  private final Map<String,Target> targets=new LinkedHashMap<>();
  private final List<AxEventSource> sources=new ArrayList<>();
  private final Map<String,CancellationToken> active=new LinkedHashMap<>();
  private boolean started;
  private final int maxAttempts;
  private final long retryBackoffMs;
  private final AxEventClock clock;
  public AxEventRuntime(List<AxEventRoute> routes){this(routes,Map.of());}
  @SuppressWarnings("unchecked")
  public AxEventRuntime(List<AxEventRoute> routes,Map<String,Object> options){this.routes=List.copyOf(routes);this.options=Map.copyOf(options);this.descriptor=(Map<String,Object>)Core.event_runtime_descriptor(routeMaps(),this.options);this.maxAttempts=((Number)options.getOrDefault("maxAttempts",3)).intValue();this.retryBackoffMs=((Number)options.getOrDefault("retryBackoffMs",1_000)).longValue();this.clock=(AxEventClock)options.getOrDefault("clock",new AxEventClock.SystemClock());this.store=new InMemoryStore(clock,options);}
  public Map<String,Object> descriptor(){return new LinkedHashMap<>(descriptor);}
  public AxEventRuntime registerTarget(Target target){targets.put(target.id,target);return this;}
  public AxEventRuntime addSource(AxEventSource source){sources.add(source);return this;}
  public AxEventRuntime start(){if(started)return this;started=true;for(AxEventSource source:sources)source.start(event->publish(event,source.identityScope(),source.trust()));return this;}
  @SuppressWarnings("unchecked")
  public List<AxEventCommand> plan(AxEventEnvelope event,String identityScope,String trust){List<Map<String,Object>> values=(List<Map<String,Object>>)Core.event_route_commands(event.toMap(),routeMaps(),identityScope,trust);Map<String,AxEventRoute> byId=new LinkedHashMap<>();for(AxEventRoute route:routes)byId.put(route.id(),route);List<AxEventCommand> out=new ArrayList<>();for(Map<String,Object> value:values){String routeId=String.valueOf(value.get("routeId"));String instanceKey=String.valueOf(value.get("instanceKey"));AxEventRoute route=byId.get(routeId);if(route.instanceKey()!=null){Object resolved=Core.event_resolve_path(Map.of("event",event.toMap(),"identity",Map.of("scope",identityScope),"trust",trust,"correlation",event.correlation()),route.instanceKey(),null);if(resolved==null)throw new IllegalArgumentException("Route "+routeId+" instance key was not present");instanceKey=String.valueOf(resolved);}out.add(new AxEventCommand(routeId,String.valueOf(value.get("action")),value.get("targetId")==null?null:String.valueOf(value.get("targetId")),instanceKey,String.valueOf(value.get("idempotencyKey"))));}return out;}
  public PublishReceipt publish(AxEventEnvelope event,String identityScope,String trust){if(!started)throw new IllegalStateException("AxEventRuntime must be started first");List<AxEventCommand> commands=plan(event,identityScope,trust);List<String> ids=new ArrayList<>();boolean duplicate=!commands.isEmpty();Map<String,AxEventRoute> byId=new LinkedHashMap<>();for(AxEventRoute route:routes)byId.put(route.id(),route);for(AxEventCommand command:commands){String id=command.routeId()+":"+event.id();ids.add(id);if(!store.deliveries.containsKey(id))duplicate=false;AxEventRoute route=byId.get(command.routeId());if(route.debounceMs()>0)for(Delivery old:store.deliveries.values())if(old.status.equals("queued")&&old.command.routeId().equals(command.routeId())&&java.util.Objects.equals(old.command.targetId(),command.targetId())&&old.command.instanceKey().equals(command.instanceKey())){old.status="coalesced";store.release(old);}store.enqueue(event,List.of(command),clock.now()+route.debounceMs());}for(String id:ids){store.deliveries.get(id).identityScope=identityScope;store.deliveries.get(id).trust=trust;}if(!duplicate)runDue();return new PublishReceipt(event.id(),true,duplicate,"volatile",List.copyOf(ids));}
  public Long nextDueAt(){Long out=null;for(Delivery value:store.deliveries.values())if(value.status.equals("queued")&&(out==null||value.availableAt<out))out=value.availableAt;return out;}
  public int runDue(){int processed=0;while(true){Delivery due=null;for(Delivery value:store.deliveries.values())if(value.status.equals("queued")&&value.availableAt<=clock.now()&&strictDeliveryEligible(value)&&(due==null||value.availableAt<due.availableAt||value.availableAt==due.availableAt&&value.sequence<due.sequence))due=value;if(due==null)return processed;due.status="running";store.release(due);dispatch(due.event,due.command,due.identityScope,due.trust);processed++;}}
  private boolean strictDeliveryEligible(Delivery candidate){List<Map<String,Object>> deliveries=new ArrayList<>();for(Delivery value:store.deliveries.values())deliveries.add(deliveryDescriptor(value));return Boolean.TRUE.equals(Core.event_strict_delivery_eligible(deliveryDescriptor(candidate),deliveries));}
  private Map<String,Object> deliveryDescriptor(Delivery value){String ordering="strict";for(AxEventRoute route:routes)if(route.id().equals(value.command.routeId())){ordering=route.ordering();break;}return Map.of("sequence",value.sequence,"targetId",value.command.targetId()==null?"":value.command.targetId(),"instanceKey",value.command.instanceKey(),"status",value.status,"ordering",ordering);}
  private Object mapTargetInput(Target target,AxEventEnvelope event,Continuation continuation,String action,String identityScope,String trust)throws Exception{InputPlan plan=action.equals("resume")?target.resumeInput:target.wakeInput;if(plan==null)plan=target.input;Object input;if(plan==null)input=target.mapInput==null?event.data():target.mapInput.map(event,continuation);else{if(target.signature==null)throw new IllegalArgumentException("Target "+target.id+" requires a signature for declarative input mapping");List<Map<String,Object>> fields=new ArrayList<>();for(Field field:target.signature.inputs)fields.add(Map.of("name",field.name,"optional",field.optional));Map<String,Object> continuationMap=continuation==null?null:Map.of("metadata",continuation.metadata);Map<String,Object> result=Core.asMap(Core.event_map_input(Map.of("event",event.toMap(),"identity",Map.of("scope",identityScope),"trust",trust,"correlation",event.correlation()),plan.toMap(),fields,continuationMap));if(!Boolean.TRUE.equals(result.get("ok")))throw new IllegalArgumentException(String.valueOf(result.get("error")));input=result.get("value");}if(target.signature!=null){List<Map<String,Object>> fields=new ArrayList<>();for(Field field:target.signature.inputs)fields.add(Map.of("name",field.name,"optional",field.optional));Map<String,Object> normalized=Core.asMap(Core.event_normalize_input(input,fields));if(!Boolean.TRUE.equals(normalized.get("ok")))throw new IllegalArgumentException(String.valueOf(normalized.get("error")));input=normalized.get("value");Core.validate_fields(target.signature.inputs,input,"input");}return input;}
  private void dispatch(AxEventEnvelope event,AxEventCommand command,String identityScope,String trust){
    String deliveryId=command.routeId()+":"+event.id();Delivery delivery=store.deliveries.get(deliveryId);Continuation continuation=null;String targetId=command.targetId();
    if(command.action().equals("resume")){continuation=findContinuation(event.correlation(),identityScope);if(continuation==null){deadLetter(deliveryId,null,null,"continuation_not_found");return;}targetId=continuation.targetId;}
    if(command.action().equals("observe")||command.action().equals("invalidate")){delivery.status="succeeded";return;}
    Target target=targets.get(targetId);if(target==null){deadLetter(deliveryId,null,null,"unknown_target:"+targetId);return;}
    String runId=delivery.runId==null?"run:"+deliveryId+":"+(store.runs.size()+1):delivery.runId;Run run=store.runs.get(runId);if(run==null){run=new Run(runId,deliveryId,command.routeId(),target.id,command.instanceKey());store.runs.put(runId,run);delivery.runId=runId;}
    CancellationToken token=new CancellationToken();active.put(runId,token);String stateKey=target.id+"\n"+identityScope+"\n"+command.instanceKey();if(target.restoreState!=null&&store.programState.containsKey(stateKey))target.restoreState.accept(store.programState.get(stateKey));
    Object input;try{input=mapTargetInput(target,event,continuation,command.action(),identityScope,trust);}catch(Exception error){run.status="failed";run.error="event_input_invalid:"+error.getMessage();deadLetter(deliveryId,runId,null,run.error);active.remove(runId);return;}
    int attempt=++delivery.attempt;run.attempt=attempt;run.status="running";
    try{
      Object output=target.invoke.invoke(input,Map.of("runId",runId,"deliveryId",deliveryId,"instanceKey",command.instanceKey(),"identityScope",identityScope,"idempotencyKey",command.idempotencyKey(),"cancellation",token));
      if(token.cancelled()){run.status="cancelled";delivery.status="cancelled";return;}
      if(target.captureState!=null)store.programState.put(stateKey,target.captureState.get());run.output=output;
      for(Map<String,Object> declaration:target.waitFor){Object raw=declaration.get("value");Object value=raw instanceof Map<?,?>?Core.event_resolve_path(Map.of("event",event.toMap(),"identity",Map.of("scope",identityScope),"trust",trust,"correlation",event.correlation()),raw,null):event.data() instanceof Map<?,?> map?map.get(String.valueOf(raw)):raw;if(value==null)throw new IllegalArgumentException("continuation value is missing");String id="continuation:"+target.id+":"+(store.continuations.size()+1);@SuppressWarnings("unchecked")Map<String,Object> metadata=(Map<String,Object>)declaration.getOrDefault("metadata",Map.of());Long expires=declaration.get("expiresInMs") instanceof Number number?clock.now()+number.longValue():null;store.continuations.put(id,new Continuation(id,target.id,command.instanceKey(),identityScope,List.of(Map.of("kind",String.valueOf(declaration.get("kind")),"value",String.valueOf(value))),metadata,expires));run.continuationIds.add(id);}
      if(run.continuationIds.isEmpty()){run.status="succeeded";delivery.status="succeeded";for(Map.Entry<String,AxEventSink> sink:target.sinks.entrySet()){try{sink.getValue().write(output,Map.of("run",run,"idempotencyKey",runId+":"+sink.getKey()));}catch(RuntimeException error){deadLetter(deliveryId,runId,sink.getKey(),error.getMessage());}}}else{run.status="waiting_event";delivery.status="waiting_event";}
      if(continuation!=null)continuation.completed=true;
    }catch(Exception error){if(attempt<maxAttempts&&target.retrySafety.equals("idempotent")){run.status="queued";store.requeue(delivery,clock.now()+retryBackoffMs*(1L<<(attempt-1)));}else{run.status=target.retrySafety.equals("idempotent")?"failed":"outcome_unknown";run.error=error.getMessage();delivery.status=run.status;deadLetter(deliveryId,runId,null,run.error);}}
    finally{active.remove(runId);}
  }
  private Continuation findContinuation(List<Map<String,String>> keys,String scope){if(keys==null)return null;for(Continuation value:store.continuations.values())if(!value.completed&&value.identityScope.equals(scope)&&(value.expiresAt==null||value.expiresAt>clock.now()))for(Map<String,String> left:value.correlation)if(keys.contains(left))return value;return null;}
  private void deadLetter(String deliveryId,String runId,String sinkId,String reason){String id="dead:"+(store.deadLetters.size()+1);store.deadLetters.put(id,new DeadLetter(id,deliveryId,runId,sinkId,reason));if(sinkId==null){Delivery delivery=store.deliveries.get(deliveryId);if(delivery!=null)delivery.status="dead_lettered";}}
  public boolean cancelRun(String runId,String reason){CancellationToken token=active.get(runId);if(token==null)return false;token.cancel(reason);return true;}
  public Run getRun(String runId){return store.runs.get(runId);}
  public List<DeadLetter> listDeadLetters(){return List.copyOf(store.deadLetters.values());}
  public void redrive(String deadId){DeadLetter dead=store.deadLetters.remove(deadId);if(dead==null)throw new IllegalArgumentException("unknown dead letter "+deadId);if(dead.sinkId()!=null){Run run=store.runs.get(dead.runId());Target target=run==null?null:targets.get(run.targetId);AxEventSink sink=target==null?null:target.sinks.get(dead.sinkId());if(run==null||target==null||sink==null){store.deadLetters.put(dead.id(),dead);throw new IllegalStateException("sink redrive state is unavailable");}try{sink.write(run.output,Map.of("run",run,"idempotencyKey",run.id+":"+dead.sinkId()));}catch(RuntimeException error){store.deadLetters.put(dead.id(),dead);throw error;}return;}Delivery delivery=store.deliveries.get(dead.deliveryId());delivery.attempt=0;store.requeue(delivery,clock.now());runDue();}
  public void close(){for(AxEventSource source:sources)source.close();started=false;}
  @SuppressWarnings("unchecked") public static Map<String,Object> normalizeMCP(String namespace,String method,Object params){return (Map<String,Object>)Core.event_normalize_mcp(namespace,method,params);}
  private List<Map<String,Object>> routeMaps(){List<Map<String,Object>> out=new ArrayList<>();for(AxEventRoute route:routes)out.add(route.toMap());return out;}
}
