import { describe, expect, it } from 'vitest';

import { AxMockAIService } from '../ai/mock/api.js';
import type { AxChatRequest, AxChatResponse } from '../ai/types.js';
import { AxMemory } from '../mem/memory.js';

import {
  processFieldProcessors,
  processStreamingFieldProcessors,
} from './fieldProcessor.js';
import { ax } from './template.js';
import type { AxFieldValue, AxGenOut } from './types.js';

describe('Field Processor Functions', () => {
  it('processFieldProcessors should execute the processor and update memory', async () => {
    // Dummy synchronous processor: converts the value to uppercase.
    const dummyProcessor = {
      field: {
        name: 'testField',
        title: 'testField',
        type: { name: 'string' as const, isArray: false },
      },
      process: async (value: AxFieldValue) => {
        if (typeof value === 'string') {
          return value.toUpperCase();
        }
        return value;
      },
    };

    const values: AxGenOut = { testField: 'hello world' };
    const mem = new AxMemory();
    const sessionId = 'session-sync';

    await processFieldProcessors([dummyProcessor], values, mem, sessionId);

    // The processor no longer updates the 'values' object directly.
    // Instead, we check that memory has been updated.
    const history = mem.history(0, sessionId);
    expect(history.length).toBe(1);

    // The message text is generated by addToMemory and will include the processed string.
    // We use toContain() to check that "HELLO WORLD" appears.
    const lastEntry = mem.getLast(sessionId);
    expect(lastEntry?.tags).toContain('processor');
    expect(lastEntry?.role).toBe('user');

    // The content is stored in the chat array
    const userMessage = history[0];
    expect(userMessage?.role).toBe('user');
    if (userMessage?.role === 'user' && Array.isArray(userMessage.content)) {
      const textContent = userMessage.content.find((c) => c.type === 'text');
      if (textContent && 'text' in textContent) {
        expect(textContent.text).toBe('HELLO WORLD');
        expect(textContent.text).not.toContain('Code Execution Result:');
        expect(textContent.text).not.toContain('was processed');
      }
    } else if (
      userMessage?.role === 'user' &&
      typeof userMessage.content === 'string'
    ) {
      expect(userMessage.content).toBe('HELLO WORLD');
      expect(userMessage.content).not.toContain('Code Execution Result:');
      expect(userMessage.content).not.toContain('was processed');
    }
  });

  it('processStreamingFieldProcessors should execute the processor and update memory without yielding any values', async () => {
    // Dummy streaming processor: appends a suffix.
    const dummyStreamingProcessor = {
      field: {
        name: 'streamField',
        title: 'streamField',
        type: { name: 'string' as const, isArray: false },
      },
      process: async (value: unknown) => {
        if (typeof value === 'string') {
          return `${value} updated`;
        }
        return value;
      },
    };

    const values: AxGenOut = { streamField: 'original' };
    const mem = new AxMemory();
    const sessionId = 'session-stream';
    // Create an extraction state with the current field set and start index 0.
    const xstate = {
      currField: dummyStreamingProcessor.field,
      s: 0,
      extractedFields: [],
      streamedIndex: {},
    };

    // Provide an initial content string.
    await processStreamingFieldProcessors(
      [dummyStreamingProcessor],
      'original',
      xstate,
      mem,
      values,
      sessionId,
      false
    );

    // Check that an assistant message is added into the session's history.
    const history = mem.history(0, sessionId);
    expect(history.length).toBe(1);

    const lastEntry = mem.getLast(sessionId);
    expect(lastEntry?.tags).toContain('processor');
    expect(lastEntry?.role).toBe('user');

    // Check the content in the history
    const userMessage = history[0];
    expect(userMessage?.role).toBe('user');
    if (userMessage?.role === 'user' && Array.isArray(userMessage.content)) {
      const textContent = userMessage.content.find((c) => c.type === 'text');
      if (textContent && 'text' in textContent) {
        expect(textContent.text).toBe('original updated');
        expect(textContent.text).not.toContain('Code Execution Result:');
        expect(textContent.text).not.toContain('was processed');
      }
    } else if (
      userMessage?.role === 'user' &&
      typeof userMessage.content === 'string'
    ) {
      expect(userMessage.content).toBe('original updated');
      expect(userMessage.content).not.toContain('Code Execution Result:');
      expect(userMessage.content).not.toContain('was processed');
    }
  });
});

describe('streaming field processor feedback', () => {
  const streamOf = (contents: string[]) =>
    new ReadableStream<AxChatResponse>({
      start(controller) {
        contents.forEach((content, i) =>
          controller.enqueue({
            results: [
              i === contents.length - 1
                ? { index: 0, content, finishReason: 'stop' }
                : { index: 0, content },
            ],
          })
        );
        controller.close();
      },
    });

  const run = async (
    feedback: (value: string) => string | null | undefined
  ) => {
    const requests: AxChatRequest<unknown>[] = [];
    const ai = new AxMockAIService<string>({
      name: 'mock',
      features: { functions: false, streaming: true },
      chatResponse: async (req) => {
        requests.push(req as AxChatRequest<unknown>);
        return streamOf(['Answer: a draft', ' then more text']) as never;
      },
    });
    const gen = ax('question:string -> answer:string');
    gen.addStreamingFieldProcessor('answer', (value: string) =>
      feedback(value)
    );
    const output = await gen.forward(
      ai,
      { question: 'q' },
      { stream: true, maxSteps: 3 }
    );
    return { output, requests };
  };

  // Feedback returned mid-stream used to be written before the rest of the
  // answer streamed in, so the run did not take another step with it.
  it('adds mid-stream feedback after the full answer and takes another step', async () => {
    let fired = false;
    const { output, requests } = await run((value) => {
      if (!fired && value.includes('draft')) {
        fired = true;
        return 'Please avoid the word draft.';
      }
      return undefined;
    });

    expect(requests).toHaveLength(2);
    expect(requests[1]!.chatPrompt.slice(-2)).toEqual([
      { role: 'assistant', content: 'Answer: a draft then more text' },
      {
        role: 'user',
        content: [{ type: 'text', text: 'Please avoid the word draft.' }],
      },
    ]);
    expect(output).toEqual({ answer: 'a draft then more text' });
  });

  // A processor that returns null used to send the text "null" as feedback
  // on every step until maxSteps ran out.
  it('treats a null result as no feedback', async () => {
    const { output, requests } = await run(() => null);

    expect(requests).toHaveLength(1);
    expect(output).toEqual({ answer: 'a draft then more text' });
  });
});
