// Generated by scripts/axir-runtime-support.mjs from
// src/ax/util/jsAnalysis.ts, src/ax/agent/contextManager.ts and
// src/ax/funcs/worker.runtime.ts. Do not edit by hand.
(function () {
function isIdentifierChar(ch) {
  return !!ch && /[A-Za-z0-9_$]/.test(ch);
}
function isIdentifierStart(ch) {
  return !!ch && /[A-Za-z_$]/.test(ch);
}
function stripJsStringsAndComments(code) {
  var _a, _b;
  let out = "";
  let i = 0;
  let state = "normal";
  let escaped = false;
  while (i < code.length) {
    const ch = (_a = code[i]) != null ? _a : "";
    const next = (_b = code[i + 1]) != null ? _b : "";
    if (state === "lineComment") {
      if (ch === "\n") {
        out += "\n";
        state = "normal";
      } else {
        out += " ";
      }
      i++;
      continue;
    }
    if (state === "blockComment") {
      if (ch === "*" && next === "/") {
        out += "  ";
        i += 2;
        state = "normal";
      } else {
        out += ch === "\n" ? "\n" : " ";
        i++;
      }
      continue;
    }
    if (state === "single" || state === "double" || state === "template") {
      const quote = state === "single" ? "'" : state === "double" ? '"' : "`";
      if (escaped) {
        out += ch === "\n" ? "\n" : " ";
        escaped = false;
        i++;
        continue;
      }
      if (ch === "\\") {
        out += " ";
        escaped = true;
        i++;
        continue;
      }
      if (ch === quote) {
        out += " ";
        state = "normal";
        i++;
        continue;
      }
      out += ch === "\n" ? "\n" : " ";
      i++;
      continue;
    }
    if (ch === "/" && next === "/") {
      out += "  ";
      i += 2;
      state = "lineComment";
      continue;
    }
    if (ch === "/" && next === "*") {
      out += "  ";
      i += 2;
      state = "blockComment";
      continue;
    }
    if (ch === "'") {
      out += " ";
      i++;
      state = "single";
      continue;
    }
    if (ch === '"') {
      out += " ";
      i++;
      state = "double";
      continue;
    }
    if (ch === "`") {
      out += " ";
      i++;
      state = "template";
      continue;
    }
    out += ch;
    i++;
  }
  return out;
}
function extractTopLevelDeclaredNames(code) {
  const names = [];
  const len = code.length;
  let i = 0;
  let braceDepth = 0;
  let parenDepth = 0;
  const skipString = (quote) => {
    i++;
    if (quote === "`") {
      let templateDepth = 0;
      while (i < len) {
        const ch = code[i];
        if (ch === "\\") {
          i += 2;
          continue;
        }
        if (templateDepth > 0) {
          if (ch === "{") {
            templateDepth++;
          } else if (ch === "}") {
            templateDepth--;
          }
          i++;
          continue;
        }
        if (ch === "$" && i + 1 < len && code[i + 1] === "{") {
          templateDepth++;
          i += 2;
          continue;
        }
        if (ch === "`") {
          i++;
          return;
        }
        i++;
      }
      return;
    }
    while (i < len) {
      const ch = code[i];
      if (ch === "\\") {
        i += 2;
        continue;
      }
      if (ch === quote) {
        i++;
        return;
      }
      i++;
    }
  };
  const skipLineComment = () => {
    i += 2;
    while (i < len && code[i] !== "\n") {
      i++;
    }
  };
  const skipBlockComment = () => {
    i += 2;
    while (i < len) {
      if (code[i] === "*" && i + 1 < len && code[i + 1] === "/") {
        i += 2;
        return;
      }
      i++;
    }
  };
  const readWord = () => {
    const start = i;
    while (i < len && isIdentifierChar(code[i])) {
      i++;
    }
    return code.slice(start, i);
  };
  const skipWhitespace = () => {
    const start = i;
    while (i < len) {
      const ch = code[i];
      if (ch === " " || ch === "	" || ch === "\n" || ch === "\r") {
        i++;
        continue;
      }
      if (ch === "/" && i + 1 < len) {
        if (code[i + 1] === "/") {
          skipLineComment();
          continue;
        }
        if (code[i + 1] === "*") {
          skipBlockComment();
          continue;
        }
      }
      break;
    }
    return i > start;
  };
  const extractDestructuredNames = (close) => {
    let depth = 1;
    while (i < len && depth > 0) {
      skipWhitespace();
      if (i >= len) return;
      const ch = code[i];
      if (ch === close) {
        depth--;
        i++;
        continue;
      }
      if (ch === "{" || ch === "[") {
        const nestedClose = ch === "{" ? "}" : "]";
        i++;
        extractDestructuredNames(nestedClose);
        continue;
      }
      if (ch === "." && i + 2 < len && code[i + 1] === "." && code[i + 2] === ".") {
        i += 3;
        skipWhitespace();
        if (i < len && isIdentifierChar(code[i])) {
          const name = readWord();
          if (name) names.push(name);
        }
        continue;
      }
      if (ch === ",") {
        i++;
        continue;
      }
      if (ch === "=") {
        i++;
        let eqDepth = 0;
        while (i < len) {
          const current = code[i];
          if (current === "'" || current === '"' || current === "`") {
            skipString(current);
            continue;
          }
          if (current === "(" || current === "[" || current === "{") {
            eqDepth++;
            i++;
            continue;
          }
          if (current === ")" || current === "]" || current === "}") {
            if (eqDepth > 0) {
              eqDepth--;
              i++;
              continue;
            }
            break;
          }
          if (current === "," && eqDepth === 0) {
            break;
          }
          i++;
        }
        continue;
      }
      if (isIdentifierChar(ch)) {
        const word = readWord();
        skipWhitespace();
        if (i < len && code[i] === ":") {
          i++;
          skipWhitespace();
          if (i < len) {
            const current = code[i];
            if (current === "{" || current === "[") {
              const nestedClose = current === "{" ? "}" : "]";
              i++;
              extractDestructuredNames(nestedClose);
            } else if (isIdentifierChar(current)) {
              const renamed = readWord();
              if (renamed) names.push(renamed);
            }
          }
        } else if (word) {
          names.push(word);
        }
        continue;
      }
      i++;
    }
  };
  const skipToCommaOrEnd = () => {
    let depth = 0;
    while (i < len) {
      const ch = code[i];
      if (ch === "'" || ch === '"' || ch === "`") {
        skipString(ch);
        continue;
      }
      if (ch === "/" && i + 1 < len) {
        if (code[i + 1] === "/") {
          skipLineComment();
          continue;
        }
        if (code[i + 1] === "*") {
          skipBlockComment();
          continue;
        }
      }
      if (ch === "(" || ch === "[" || ch === "{") {
        depth++;
        i++;
        continue;
      }
      if (ch === ")" || ch === "]" || ch === "}") {
        if (depth > 0) {
          depth--;
          i++;
          continue;
        }
        return false;
      }
      if (ch === "," && depth === 0) {
        i++;
        return true;
      }
      if (ch === ";" && depth === 0) {
        i++;
        return false;
      }
      if (ch === "\n" && depth === 0) {
        const savedIndex = i;
        i++;
        skipWhitespace();
        if (i < len && code[i] === ",") {
          i++;
          return true;
        }
        i = savedIndex;
        return false;
      }
      i++;
    }
    return false;
  };
  const extractBindings = () => {
    while (i < len) {
      skipWhitespace();
      if (i >= len) return;
      const ch = code[i];
      if (ch === "{") {
        i++;
        extractDestructuredNames("}");
        if (!skipToCommaOrEnd()) return;
        continue;
      }
      if (ch === "[") {
        i++;
        extractDestructuredNames("]");
        if (!skipToCommaOrEnd()) return;
        continue;
      }
      if (isIdentifierChar(ch)) {
        const name = readWord();
        if (name) names.push(name);
        if (!skipToCommaOrEnd()) return;
        continue;
      }
      return;
    }
  };
  const isStatementBoundary = (pos) => {
    if (pos === 0) return true;
    let j = pos - 1;
    while (j >= 0) {
      const ch = code[j];
      if (ch === " " || ch === "	" || ch === "\r") {
        j--;
        continue;
      }
      return ch === "\n" || ch === ";" || ch === "{" || ch === "}";
    }
    return true;
  };
  while (i < len) {
    const ch = code[i];
    if (ch === "'" || ch === '"' || ch === "`") {
      skipString(ch);
      continue;
    }
    if (ch === "/" && i + 1 < len) {
      if (code[i + 1] === "/") {
        skipLineComment();
        continue;
      }
      if (code[i + 1] === "*") {
        skipBlockComment();
        continue;
      }
    }
    if (ch === "{") {
      braceDepth++;
      i++;
      continue;
    }
    if (ch === "}") {
      braceDepth--;
      i++;
      continue;
    }
    if (ch === "(") {
      parenDepth++;
      i++;
      continue;
    }
    if (ch === ")") {
      parenDepth--;
      i++;
      continue;
    }
    if (braceDepth === 0 && parenDepth === 0 && isIdentifierChar(ch)) {
      const wordStart = i;
      const word = readWord();
      if ((word === "var" || word === "let" || word === "const") && i < len && (code[i] === " " || code[i] === "	" || code[i] === "\n") && isStatementBoundary(wordStart)) {
        extractBindings();
      }
      continue;
    }
    i++;
  }
  const seen = /* @__PURE__ */ new Set();
  const unique = [];
  for (const name of names) {
    if (!seen.has(name)) {
      seen.add(name);
      unique.push(name);
    }
  }
  return unique;
}
function extractTopLevelDurableWriteTargets(code) {
  const names = new Set(extractTopLevelDeclaredNames(code));
  const sanitized = stripJsStringsAndComments(code);
  const len = sanitized.length;
  let i = 0;
  let braceDepth = 0;
  let parenDepth = 0;
  const skipWhitespace = (index) => {
    var _a;
    let current = index;
    while (current < len && /\s/.test((_a = sanitized[current]) != null ? _a : "")) {
      current++;
    }
    return current;
  };
  const previousNonWhitespaceIndex = (index) => {
    var _a;
    let current = index;
    while (current >= 0 && /\s/.test((_a = sanitized[current]) != null ? _a : "")) {
      current--;
    }
    return current;
  };
  const isAssignmentOperatorAt = (index) => {
    const threeChars = sanitized.slice(index, index + 3);
    const twoChars = sanitized.slice(index, index + 2);
    if (threeChars === "===" || twoChars === "==" || twoChars === "=>") {
      return false;
    }
    return sanitized[index] === "=" || [
      "+=",
      "-=",
      "*=",
      "/=",
      "%=",
      "&=",
      "|=",
      "^=",
      "&&=",
      "||=",
      "??=",
      "**=",
      "<<=",
      ">>=",
      ">>>="
    ].some((op) => sanitized.startsWith(op, index));
  };
  const readWord = (start) => {
    let nextIndex = start;
    while (nextIndex < len && isIdentifierChar(sanitized[nextIndex])) {
      nextIndex++;
    }
    return { word: sanitized.slice(start, nextIndex), nextIndex };
  };
  const addIfBareAssignment = (word, start, end) => {
    const prevIndex = previousNonWhitespaceIndex(start - 1);
    const prev = prevIndex >= 0 ? sanitized[prevIndex] : void 0;
    const nextIndex = skipWhitespace(end);
    const isMemberAccess = prev === "." || prev === "?";
    if (isMemberAccess) {
      return;
    }
    const hasPrefixUpdate = sanitized.slice(Math.max(0, start - 2), start) === "++" || sanitized.slice(Math.max(0, start - 2), start) === "--";
    const hasSuffixUpdate = sanitized.startsWith("++", nextIndex) || sanitized.startsWith("--", nextIndex);
    if (hasPrefixUpdate || hasSuffixUpdate || isAssignmentOperatorAt(nextIndex)) {
      names.add(word);
    }
  };
  const addIfGlobalAssignment = (start, end) => {
    const dotIndex = skipWhitespace(end);
    if (sanitized[dotIndex] !== ".") {
      return;
    }
    const nameStart = skipWhitespace(dotIndex + 1);
    if (!isIdentifierStart(sanitized[nameStart])) {
      return;
    }
    const { word: propertyName, nextIndex } = readWord(nameStart);
    const operatorIndex = skipWhitespace(nextIndex);
    const hasPrefixUpdate = sanitized.slice(Math.max(0, start - 2), start) === "++" || sanitized.slice(Math.max(0, start - 2), start) === "--";
    const hasSuffixUpdate = sanitized.startsWith("++", operatorIndex) || sanitized.startsWith("--", operatorIndex);
    if (propertyName && (hasPrefixUpdate || hasSuffixUpdate || isAssignmentOperatorAt(operatorIndex))) {
      names.add(propertyName);
    }
  };
  while (i < len) {
    const ch = sanitized[i];
    if (ch === "{") {
      braceDepth++;
      i++;
      continue;
    }
    if (ch === "}") {
      braceDepth--;
      i++;
      continue;
    }
    if (ch === "(") {
      parenDepth++;
      i++;
      continue;
    }
    if (ch === ")") {
      parenDepth--;
      i++;
      continue;
    }
    if (braceDepth === 0 && parenDepth === 0 && isIdentifierStart(ch)) {
      const start = i;
      const { word, nextIndex } = readWord(i);
      i = nextIndex;
      if (!word) {
        continue;
      }
      if (word === "globalThis") {
        addIfGlobalAssignment(start, nextIndex);
        continue;
      }
      addIfBareAssignment(word, start, nextIndex);
      continue;
    }
    i++;
  }
  return [...names];
}
const JS_KEYWORDS = new Set([
  'var', 'let', 'const', 'function', 'return', 'if', 'else', 'for', 'while',
  'do', 'switch', 'case', 'break', 'continue', 'try', 'catch', 'finally',
  'throw', 'new', 'delete', 'typeof', 'void', 'in', 'of', 'instanceof',
  'this', 'class', 'extends', 'super', 'import', 'export', 'default', 'from',
  'as', 'async', 'await', 'yield', 'true', 'false', 'null', 'undefined',
  'console', 'log'
]);
function extractReferencedIdentifiers(code) {
  const sanitized = stripJsStringsAndComments(code);
  const identRegex = /\b([a-zA-Z_$][a-zA-Z0-9_$]*)\b/g;
  const ids = new Set();
  let match = identRegex.exec(sanitized);
  while (match !== null) {
    if (match[1] && !JS_KEYWORDS.has(match[1])) {
      ids.add(match[1]);
    }
    match = identRegex.exec(sanitized);
  }
  return ids;
}
function extractReadIdentifiers(code) {
  const reads = extractReferencedIdentifiers(code);
  for (const declared of extractTopLevelDeclaredNames(code)) {
    reads.delete(declared);
  }
  return reads;
}
function extractDirectQualifiedCallableUsages(code) {
  const sanitized = stripJsStringsAndComments(code);
  const usages = new Set();
  const callPattern = /\b([a-zA-Z_$][a-zA-Z0-9_$]*)\.([a-zA-Z_$][a-zA-Z0-9_$]*)\s*\(/g;
  let match = callPattern.exec(sanitized);
  while (match) {
    const namespace = match[1];
    const name = match[2];
    if (namespace && name) {
      usages.add(namespace + '.' + name);
    }
    match = callPattern.exec(sanitized);
  }
  return [...usages];
}
const truncateInspectText = (text, maxChars) =>
  text.length <= maxChars ? text : text.slice(0, maxChars - 3) + '...';
const previewInspectAtom = (value) => {
  if (value === null) {
    return 'null';
  }
  if (value === undefined) {
    return 'undefined';
  }
  const valueType = typeof value;
  if (typeof value === 'string') {
    return JSON.stringify(truncateInspectText(value, 40));
  }
  if (valueType === 'number' || valueType === 'boolean' || valueType === 'bigint') {
    return String(value);
  }
  if (valueType === 'symbol') {
    return String(value);
  }
  if (valueType === 'function') {
    const fnName = value.name && typeof value.name === 'string' ? value.name : '';
    return '[function ' + (fnName || 'anonymous') + ']';
  }
  if (Array.isArray(value)) {
    return '[array(' + value.length + ')]';
  }
  if (value instanceof Date) {
    return Number.isFinite(value.getTime()) ? value.toISOString() : String(value);
  }
  if (value instanceof Error) {
    return (value.name || 'Error') + ': ' + (value.message || '');
  }
  if (typeof Map !== 'undefined' && value instanceof Map) {
    return '[map(' + value.size + ')]';
  }
  if (typeof Set !== 'undefined' && value instanceof Set) {
    return '[set(' + value.size + ')]';
  }
  const ctorName =
    value && typeof value === 'object' && 'constructor' in value && value.constructor &&
    typeof value.constructor.name === 'string'
      ? value.constructor.name
      : '';
  return ctorName && ctorName !== 'Object' ? '[' + ctorName + ']' : '[object]';
};
const describeInspectType = (value) => {
  if (value === null) {
    return { type: 'null' };
  }
  if (Array.isArray(value)) {
    return { type: 'array', ctor: 'Array' };
  }
  if (typeof Map !== 'undefined' && value instanceof Map) {
    return { type: 'map', ctor: 'Map' };
  }
  if (typeof Set !== 'undefined' && value instanceof Set) {
    return { type: 'set', ctor: 'Set' };
  }
  if (value instanceof Date) {
    return { type: 'date', ctor: 'Date' };
  }
  if (value instanceof Error) {
    return {
      type: 'error',
      ctor: typeof value.name === 'string' && value.name.trim() ? value.name : 'Error',
    };
  }
  const valueType = typeof value;
  if (valueType !== 'object') {
    return { type: valueType };
  }
  const ctor =
    value && typeof value === 'object' && 'constructor' in value && value.constructor &&
    typeof value.constructor.name === 'string'
      ? value.constructor.name
      : undefined;
  return { type: 'object', ctor };
};
const describeInspectSize = (value, type) => {
  if (type === 'string') {
    return value.length + ' chars';
  }
  if (type === 'array') {
    return value.length + ' items';
  }
  if (type === 'map' || type === 'set') {
    return value.size + ' items';
  }
  if (type === 'object' && value && typeof value === 'object') {
    return Object.keys(value).length + ' keys';
  }
  return undefined;
};
const previewInspectValue = (value, type, ctor) => {
  if (type === 'array') {
    const items = value.slice(0, 3).map((item) => previewInspectAtom(item));
    return '[' + items.join(', ') + (value.length > 3 ? ', ...' : '') + ']';
  }
  if (type === 'map') {
    const items = Array.from(value.entries())
      .slice(0, 3)
      .map((pair) => previewInspectAtom(pair[0]) + ' => ' + previewInspectAtom(pair[1]));
    return 'Map(' + value.size + ') {' + items.join(', ') + (value.size > 3 ? ', ...' : '') + '}';
  }
  if (type === 'set') {
    const items = Array.from(value.values())
      .slice(0, 5)
      .map((item) => previewInspectAtom(item));
    return 'Set(' + value.size + ') {' + items.join(', ') + (value.size > 5 ? ', ...' : '') + '}';
  }
  if (type === 'date' || type === 'error' || type === 'function') {
    return previewInspectAtom(value);
  }
  if (type === 'object' && value && typeof value === 'object') {
    const keys = Object.keys(value);
    const shown = keys.slice(0, 4);
    const prefix = ctor && ctor !== 'Object' ? ctor + ' ' : '';
    return prefix + '{' + shown.join(', ') + (keys.length > shown.length ? ', ...' : '') + '}';
  }
  return previewInspectAtom(value);
};
const canCloneValue = (value, seen) => {
  const valueType = typeof value;
  if (valueType === 'function' || valueType === 'symbol') {
    return false;
  }
  if (value === null || valueType !== 'object') {
    return true;
  }
  if (seen.indexOf(value) >= 0) {
    return true;
  }
  seen.push(value);
  if (value instanceof Date || value instanceof RegExp || value instanceof Error) {
    return true;
  }
  if (typeof Map !== 'undefined' && value instanceof Map) {
    for (const pair of value.entries()) {
      if (!canCloneValue(pair[0], seen) || !canCloneValue(pair[1], seen)) return false;
    }
    return true;
  }
  if (typeof Set !== 'undefined' && value instanceof Set) {
    for (const item of value.values()) {
      if (!canCloneValue(item, seen)) return false;
    }
    return true;
  }
  for (const key of Object.keys(value)) {
    if (!canCloneValue(value[key], seen)) return false;
  }
  return true;
};
globalThis.__ax_analyze_code = function (code) {
  const text = typeof code === 'string' ? code : '';
  return JSON.stringify({
    producedVars: extractTopLevelDurableWriteTargets(text),
    readVars: [...extractReadIdentifiers(text)],
    callables: extractDirectQualifiedCallableUsages(text),
  });
};
// src/ax/agent/agentInternal/sharedSession.ts buildDistillerFinalWrapperCode:
// in the distiller phase, final(task, evidence) with an evidence object
// keeps it as the distilledContext global, which the executor inherits with
// the session. The runtime calls this after installing its final primitive;
// a merge patch (the executor phase) sets __ax_phase to 'executor'.
globalThis.__ax_install_final_evidence = function () {
  const hostFinal = globalThis.final;
  if (typeof hostFinal !== 'function' || hostFinal.__ax_final_evidence === true) {
    return;
  }
  const wrapped = function () {
    const context = arguments[1];
    if (
      globalThis.__ax_phase !== 'executor' &&
      arguments.length === 2 &&
      context !== null &&
      typeof context === 'object' &&
      !Array.isArray(context)
    ) {
      globalThis.distilledContext = context;
    }
    return hostFinal.apply(this, arguments);
  };
  wrapped.__ax_final_evidence = true;
  const descriptor = Object.getOwnPropertyDescriptor(globalThis, 'final') || {};
  try {
    if (descriptor.configurable === false) {
      globalThis.final = wrapped;
    } else {
      Object.defineProperty(globalThis, 'final', {
        value: wrapped,
        writable: descriptor.writable !== false,
        enumerable: descriptor.enumerable === true,
        configurable: true,
      });
    }
  } catch (_error) {
    // A final the runtime cannot replace keeps its behavior.
  }
};
globalThis.__ax_inspect_entries = function (skipNames) {
  const skip = new Set(Array.isArray(skipNames) ? skipNames : []);
  const scope = globalThis;
  const entries = Object.getOwnPropertyNames(scope)
    .filter((name) => !skip.has(name) && !name.startsWith('_'))
    .sort()
    .map((name) => {
      try {
        const descriptor = Object.getOwnPropertyDescriptor(scope, name);
        if (!descriptor) {
          return undefined;
        }
        if ('get' in descriptor && typeof descriptor.get === 'function' && !('value' in descriptor)) {
          return { name, type: 'accessor', preview: '[getter omitted]', restorable: false };
        }
        const value = 'value' in descriptor ? descriptor.value : scope[name];
        const meta = describeInspectType(value);
        const size = describeInspectSize(value, meta.type);
        const preview = previewInspectValue(value, meta.type, meta.ctor);
        const entry = { name, type: meta.type };
        if (meta.ctor) entry.ctor = meta.ctor;
        if (size) entry.size = size;
        if (preview) entry.preview = truncateInspectText(preview, 96);
        entry.restorable = canCloneValue(value, []);
        return entry;
      } catch (_error) {
        return { name, type: 'unknown', preview: '[unavailable]', restorable: false };
      }
    })
    .filter((entry) => entry !== undefined);
  return JSON.stringify(entries);
};
})();
