name: Pull Request CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # You can specify your desired Node.js version
      - name: Install dependencies
        run: npm ci
